README.md, docs/how_we_work.md
[Preview link.](https://github.com/18F/OPRE-MAPS/blob/ars/23/how-we-work-eng-practices/docs/how_we_work.md) 👁️ 
GitHub card: https://github.com/18F/OPRE-MAPS/issues/23.
Content via [[draft] Engineering team practices & norms in Drive](https://docs.google.com/document/d/1lxIvzeqQV4wQ6jG5IYtDTtn84fIJTCYCDwGaUSzBaTQ/edit#).🔒
=> How we work: Engineering team practices & norms

docs/adr/004-database.md
+ Adds ADR for database
[Preview link for folder.](https://github.com/18F/OPRE-MAPS/tree/aym/25/tech-stack/docs/adr) 👁️ 
Completes part of #25.
=> Add ADR for database

docs/adr/004-use-postgresql-for-database.md
- Renamed ADR for database to include the choice and use of active voice
- Added "Options Considered" section to resolve [comment](https://github.com/18F/OPRE-Unicorn/pull/58#pullrequestreview-701243277) from PR #58
[Preview link for `004-use-postgresql-for-database.md`.](https://github.com/18F/OPRE-Unicorn/blob/aym/25/database/docs/adr/004-use-postgresql-for-database.md) 👁️ 
Completes part of #25.
=> Updated and renamed ADR for database to include Options Considered section

docs/adr/006-start-off-with-server-side-rendering.md
Adds ADR for front-end tech stack.
[Preview link.](https://github.com/18F/OPRE-Unicorn/blob/ars/25/start-off-with-server-side-rendering.md/docs/adr/006-start-off-with-server-side-rendering.md) 👁️ 
This should complete #25!
=> Front-end tech stack: Start off with server-side rendering

docs/adr/007-use-s3-for-document-storage.md
+ Adds ADR for document storage
[Preview link for folder.](https://github.com/18F/OPRE-MAPS/tree/aym/68/storage/docs/adr/007-use-s3-for-document-storage.md) 👁️ 
Completes #68.
=> Add ADR for Document Storage

docs/adr/002-use-cloud-dot-gov.md, docs/adr/003-use-github-for-version-control.md, docs/adr/005-use-django-for-back-end-web-framework.md, docs/adr/007-use-s3-for-document-storage.md
There are a few ADRs that have already been merged that are still in the "Proposed" state.  Since they have all been reviewed and approved by the team, they should be in the "Accepted" state.
https://github.com/18F/OPRE-Unicorn/tree/aym/68/accept-adrs/docs/adr
=> Change all ADR status from Proposed to Accepted

docs/adr/008-use-circle-for-ci-cd.md
+ Adds ADR for decision to use CircleCI for CI/CD
[Preview link.](https://github.com/18F/OPRE-Unicorn/blob/ars/55/adr-for-circle-ci/docs/adr/008-use-circle-for-ci-cd.md) 👁️ 
Completes #55.
=> ADR for CI/CD choice

.gitignore
+ https://github.com/github/gitignore
+ Closes #51 .
This file is created from the [`Python.gitignore` template](https://github.com/github/gitignore/blob/master/Python.gitignore).
I am starting with Python gitignore because majority of the code is Python.  This is a starting point, and this file will need to be updated as we add different languages and tools, i.e. JavaScript, code coverage, security analysis tools.
There are definitely different approaches we can take on writing this file.  We can start from bare minimum, or start with the given template.  The latter is the choice I made here.
=> Create .gitignore to prevent accidentally merging in secrets and transient files

docs/how_we_work/issue_review.md
Adds documentation for our reviews process.
Establish overall team processes #31 
https://github.com/18F/OPRE-Unicorn/blob/7f893d56af0d9d3bd445dfe26d62e9c0e9b0b590/docs/how_we_work/issue_review.md
=> Issue 31: Add review process markdown to how_we_work docs

requirements.txt
Testing dependabot, will revert once we see dependabot works.
=> Add out of date package to test dependabot

.github/pull_request_template.md
Introduces a new pull request template!
#187.
👁️ [pull_request_template.md](https://github.com/HHS/OPRE-OPS/blob/ars/187/pr-template/.github/pull_request_template.md)
=> Propose initial pull request template

.circleci/config.yml
_Described what changes in this PR, at a high level_ 
_Write out steps for how someone could test this PR against the conditions of acceptance_ 
=> fix typo in bash string

docs/adr/008-use-circle-for-ci-cd.md, docs/recipes/setup_circleci.md
Adds documentation for CircleCI and cloud.gov deployment setup
https://github.com/HHS/OPRE-OPS/blob/1c80119671b47e8d129cc3d6f7978d1c525659a8/docs/recipes/setup_circleci.md
=> Update docs for circle

README.md
An addition to the README, describing the process I needed to use pipenv
Run the commands in the README
=> Add pipenv verify and install to README

opre_ops/opre_ops/settings/common.py
As an experiment, modify the `PROJECT_DIR` to use the parent directory of the previous location
To fix the CSS
Look at the deployed webpages and see if the CSS is broken
=> Experiment with putting static files in parent directory

opre_ops/opre_ops/settings/common.py
_Described what changes in this PR, at a high level_ 
_Write out steps for how someone could test this PR against the conditions of acceptance_ 
=> Another experiment, hard-coding the PROJECT_DIR variable

opre_ops/opre_ops/settings/common.py
_Described what changes in this PR, at a high level_ 
_Write out steps for how someone could test this PR against the conditions of acceptance_ 
=> Try removing the `/static` from the PROJECT_DIR variable string

opre_ops/opre_ops/settings/common.py
Try changing the PROJECT_DIR variable to contain `ops_site` because of advice on Slack
Trying to fix the deployed CSS
=> Trying a PROJECT_DIR following advice in cg-support

opre_ops/opre_ops/settings/common.py
Remove `/home/vcap/app` as an experiment, per cg-support on Slack
Trying to fix deployed CSS
=> Remove first part of path, as an experiment

opre_ops/opre_ops/settings/common.py
Restore left-hand side of the path, then try `opre_ops/ops_site/opre_ops` I guess
Trying to fix the CSS
=> Restore left-hand side of path, try different directory

opre_ops/opre_ops/settings/common.py
Remove one level from the PROJECT_DIR variable, as an experiment to find where static assets belong
Deployed CSS broken
=> Remove one directory level from PROJECT_DIR

manifest.yml
Include `--noinput` on the `collectstatic` command to allow overwrite of `.keep` files
deployment CSS broken
=> Include --noinput on my collectstatic command

opre_ops/opre_ops/settings/common.py
Experimentally remove another level of the PROJECT_DIR
=> Remove another directory of the PROJECT_DIR variable

opre_ops/opre_ops/settings/common.py
Experimentally removed another level of the PROJECT_DIR variable
=> Experimentally remove another level of PROJECT_DIR

opre_ops/opre_ops/settings/common.py
Try yet another path in PROJECT_DIR path variable
=> Try yet another path in PROJECT_DIR variable

opre_ops/opre_ops/settings/common.py
Remove hardcoded path, try nested dirname()s
=> Remove hardcoded path, try nested `dirname()`s

opre_ops/opre_ops/settings/common.py
Experiment with the `STATICFILES_DIRS` variable, setting several paths
=> Experiment with the STATICFILES_DIRS variable

opre_ops/opre_ops/settings/common.py
Copy `STATIC_ROOT` and other variables from TANF data portal
=> Copy code from TANF data portal

README.md, docs/recipes/setup_circleci.md
Add deployment details to the README and recipes
Re-deploy or restage the app according to instructions
=> Deployment in readme

docs/adr/001-record-architecture-decisions.md, docs/adr/003-use-github-for-version-control.md, docs/adr/004-use-postgresql-for-database.md, docs/adr/007-use-s3-for-document-storage.md
Replacing references to deprecated project name, fixing typos, and other minor additions
=> correcting deprecated names and typos in ADRs

docs/adr/002-use-cloud-dot-gov.md
Updated the Cloud.gov ADR based on our latest re-evaulation.
#300.
=> 300: Update Cloud.gov ADR

.flake8, .github/workflows/ci.yml, Dockerfile, noxfile.py, opre_ops/opre_ops/settings/cloudgov.py, opre_ops/opre_ops/settings/common.py, opre_ops/opre_ops/settings/helpers/random_string.py, opre_ops/opre_ops/settings/local.py, opre_ops/ops_site/admin.py, opre_ops/ops_site/helpers/csv_to_json.py, opre_ops/ops_site/models.py, opre_ops/ops_site/urls.py, opre_ops/ops_site/views.py
Fixes all the linting issues.
Enforces all the linting issues are fixed in CI.
#304
=> 304: Fix Linting Issues and Enforce Linting in CI

.github/workflows/dev_deploy.yml, manifest.yml
Set up the `manifest.yml` to deploy the frontend to Cloud.gov.
#304
https://opre-ops-frontend-test-sweet-sable-ir.app.cloud.gov
=> 304: Deploy the Frontend to Cloud.gov

docs/adr/012-use-pre-commit-hooks.md
Added ADR for Pre-Commit decision
#333
=> created ADR for 333

README.md
adding the new frontend URL back to README from #337
=> a new frontend protopye url is born

README.md, docs/adr/011-github-actions-for-ci-cd.md, docs/adr/012-use-pre-commit-hooks.md
Minor updates to README.md and 012-ADR
PRs were committed without applying suggested changes.
=> documentation updates

.github/ISSUE_TEMPLATE/feature_work_template.md
Adding a feature issue (story) default definition of done, to be customized for each story as appropriate. 
N/A
N/A
N/A 
N/A
=> adding condensed version of default DoD to issue template

backend/opre_ops/manage.py, manifest.yml
Had to muck with the `PYTHONPATH` with the how it is deployed to Cloud.gov.
#304
=> 304: Fix the deployment to Cloud.gov given the refactor of the backend

README.md
Updated the `README.md` based on all the changes we've made.  I also slimmed it down a little bit.
#304.
=> 304: Read Me

docs/adr/014-use-cypress-for-testing.md
=> new adr for cypress

.github/workflows/ci.yml, .github/workflows/security_semgrep.yml, .secrets.baseline, backend/Dockerfile, backend/opre_ops/django_config/settings/common.py, docker-compose.yml, frontend/Dockerfile
- Added Semgrep Scans to CI
- Cleaned up any prior existing Semgrep findings
#304
=> Issue 304 automate security

docker-compose.yml
We recently moved to copy over our application code to `/home/app` in the `Dockerfile`s.  Now we specify that for the volumes in our `docker-compose.yml` file.
=> Specify /home/app in the docker-compose file

.github/workflows/security_semgrep.yml
- Attempts to fix the GH Action permission issue on `merge`
=> Action Permission Fix

.github/workflows/ci.yml, .github/workflows/security_semgrep.yml
- Added `security-events: write` to permissions
=> adding security-events writable permission

backend/Dockerfile, backend/Pipfile, backend/Pipfile.lock, backend/opre_ops/django_config/asgi.py, backend/opre_ops/django_config/wsgi.py, docker-compose.yml, manifest.yml
We now use the [Uvicorn](https://www.uvicorn.org) as the application (ASGI) server.  We also use [Gunicorn](https://gunicorn.org) as the worker supervisor.
#376
=> 376: Uvicorn & Gunicorn

.github/workflows/security_semgrep.yml
=> Add GH Secret for Semgrep

frontend/src/pages/cans/list/CanList.jsx
Convert the CAN list page to the USWDS.
#376.
http://localhost:3000/cans
=> 376: Convert CAN List Page to USWDS

frontend/src/pages/portfolios/list/PortfolioList.jsx
Convert the Portfolio list page to the USWDS.
#376.
http://localhost:3000/portfolios
=> 376: Convert Portfolio List Page to the USWDS

frontend/src/pages/cans/detail/CanDetail.jsx, frontend/src/pages/cans/detail/budgetSummary/BudgetSummary.jsx
Convert the CAN detail page to the USWDS.
I also removed a lot of extra hardcoded tables that were just sitting there.
#376.
http://localhost:3000/cans/3
=> 376: Convert CAN Detail Page to the USWDS

frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Convert the Portfolio detail page to the USWDS.
#376.
http://localhost:3000/portfolios/1
=> 376: Convert Portfolio Detail Page to USWDS

.github/workflows/ci.yml, .github/workflows/security_codeql.yml, .github/workflows/security_semgrep.yml, .secrets.baseline, backend/opre_ops/django_config/settings/cloudgov.py, backend/opre_ops/django_config/settings/local.py, backend/opre_ops/django_config/settings/test.py, frontend/src/pages/cans/detail/CanDetail.jsx, frontend/src/pages/cans/detail/budgetSummary/BudgetSummary.jsx, frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
- Added CodeQL to Security Scans Action
- Added `development` branch to CI workflow for `pull`s
=> adding code-ql scans; added `development` to ci

.github/actions/deploy-backend/action.yml, .github/actions/deploy-frontend/action.yml, .github/actions/setup-cloudfoundry/action.yml, .github/workflows/dev_deploy.yml
Fix bugs on main.
N/A
Test locally and https://opre-ops-frontend-test.app.cloud.gov/
=> Fix gha setup cf

backend/ops_api/django_config/apps.py, docs/adr/015-a11y-testing.md
An ADR for a11y testing.
#376.
=> 376: A11y Testing ADR

.github/ISSUE_TEMPLATE/feature_work_template.md
Updating default Definition of Done in the feature issue template to reflect the idea that both additions or changes need to take place to our testing regime as well as all tests passing.
=> Update DoD 

backend/deployed_run.sh, manifest.yml
* Updated application names to match the new cloud.gov environment
* updated `space` name to match the new cloud.gov environment
* updated credentials in github secrets
#503
=> Issue-503-update-cloud_gov-release

backend/Pipfile, backend/Pipfile.lock, frontend/package.json, frontend/yarn.lock
Updated the manifest and deploy script to match new environment.
#503
=> Release to new cloud env.

frontend/package.json, frontend/src/index.css, frontend/src/index.jsx, frontend/yarn.lock
Override USWDS default sans font and fix font size px. 
http://localhost:3000/portfolios/10
=> Ops change default font

backend/ops_api/ops/environment/cloud.py, manifest.yml
* Added DB Connection info for flask backend
#499
Check the live environment after deployment
=> added cloud config for db connection

frontend/cypress/e2e/portfolioDetail.cy.js, frontend/src/components/CanCard/CanCard.jsx, frontend/src/components/UI/Tag/styles.module.css
* Updated the formatting of the Budget Status table items to use `CurrencyWithSmallCents` component
* Very small tweak to the `Tag` for vertical spacing. There is a browser compatibility issue here that might need to be discussed.
#479 
See screenshot
=> added Currency format

frontend/cypress/e2e/portfolioDetail.cy.js, frontend/src/components/PortfolioDescription/PortfolioDescription.jsx, frontend/src/components/PortfolioFundingByCAN/PortfolioFundingByCAN.jsx, frontend/src/components/PortfolioFundingByCAN/styles.module.css, frontend/src/components/PortfolioFundingSummary/PortfolioFundingSummary.jsx, frontend/src/pages/portfolios/detail/PortfolioDetail.jsx, frontend/src/pages/portfolios/detail/getPortfolioCans.js, frontend/src/pages/portfolios/detail/portfolioDetailSlice.js
Added Portfolio Funding by CAN Card.
[_Add link to issue here_](https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/hhs/opre-ops/561)
Currently in local dev only.
=> Ops 561 portfolio cans

frontend/src/components/UI/CurrencyWithSmallCents/CurrencyWithSmallCents.jsx, frontend/src/components/UI/CurrencyWithSmallCents/util.js, frontend/src/components/UI/CurrencyWithSmallCents/util.test.js, frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Requirements changes for displaying $0
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/595
https://ops-dev.fr.cloud.gov/
=> Ops 595 zero dollar merged

.github/renovate.json
* Updated Renovate Config `.github/renovate.json` to include `pinGitHubActionDigests`
https://docs.renovatebot.com/modules/manager/github-actions/
=> add `pinGetHubActionDigests`

frontend/cypress/e2e/portfolioDetail.cy.js, frontend/src/components/Portfolios/BudgetAndFunding/BudgetAndFunding.jsx, frontend/src/components/Portfolios/PeopleAndTeams/PeopleAndTeams.jsx, frontend/src/components/Portfolios/PeopleAndTeams/PeopleAndTeams.module.css, frontend/src/components/Portfolios/PeopleAndTeams/PeopleAndTeams.test.js, frontend/src/components/Portfolios/ResearchProjects/ResearchProjects.jsx, frontend/src/components/Portfolios/ResearchProjects/ResearchProjects.module.css, frontend/src/components/Portfolios/ResearchProjects/ResearchProjects.test.js, frontend/src/components/Portfolios/TabsSection/TabsSection.jsx, frontend/src/components/Portfolios/TabsSection/TabsSection.module.css, frontend/src/components/Portfolios/TabsSection/TabsSection.test.js, frontend/src/components/UI/FiscalYear/FiscalYear.jsx, frontend/src/components/UI/FiscalYear/FiscalYear.module.css, frontend/src/index.jsx, frontend/src/pages/PortfolioDetail.jsx
Made TabsSection component functional on Portfolio Details page.
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/490
https://ops-dev.fr.cloud.gov/
=> Ops 490 portfolio tabs

frontend/cypress/e2e/portfolioDetail.cy.js, frontend/src/components/Portfolios/TabsSection/TabsSection.jsx
Label names are  consistent in  Tab navigation
inconsistant casing ie And/and
In portfolio view, look at the secondary nav, ie Tabs, and make sure  they are consistant. 
- and should be (lowercase)
=> consistent Tab labels

backend/ops_api/ops/utils/auth_views.py, frontend/src/helpers/backend.js
=> Deployment Fixes

.secrets.baseline, openapi.yml
- Initial take at creating an OpenApi.yml spec file. 
We will add more to this, and refactor as needed (`parameters`, `schema`, etc.)
=> TechDebt-OpenAPI

.secrets.baseline, backend/Dockerfile.ops-api, backend/ops_api/deployed_run.sh, backend/ops_api/ops/environment/cloud/dev.py, backend/ops_api/ops/environment/cloud/prod.py, backend/ops_api/ops/environment/local/container.py, backend/ops_api/ops/environment/local/e2e.py, backend/ops_api/ops/environment/local/localhost.py, backend/ops_api/ops/utils/auth_views.py, frontend/src/helpers/backend.js, manifest.yml, openapi.yml
* Updated versions of PIP, PIPENV for deployments
* updated opeapi to include better descriptors
* Fixed bug where deployed site `redirect_url` was broken (hardcoded to localhost)
=> TechDebt Bug Fixes

backend/data_tools/data/user_data.json5, backend/models/users.py, backend/ops_api/ops/utils/user.py, frontend/src/helpers/backend.js
* Fixed a bug, where a non-registered user could not login; result of the User model needing the Identity filed specified.
=> TechDebt - Fix User model, and login bug

frontend/src/components/UI/Header/User.jsx, frontend/src/components/Users/UserInfo/UserInfo.jsx
- shows OIDC on user detail page
- shows email when first and last name are not present
Login and see your email  instead of `null null`. 
Go to user detail page and see your OIDC.
=> user improvements

frontend/src/components/Portfolios/ResearchProjects/AdminAndSupportProjectsTable.jsx, frontend/src/components/Portfolios/ResearchProjects/ResearchProjectsTable.jsx
better hover styles on table headings
UX feedback
Hover over table headings and they should stay black.
=> better hover styles on table headings

frontend/src/index.jsx
adds uswds javascript
no uswds  js
Add  a banner and  see if it  opens and closes
https://user-images.githubusercontent.com/4629398/224367704-658470c4-bec0-449d-bc49-0925f877e31e.mov
Banner comp: https://designsystem.digital.gov/components/banner/
=> adds uswds javascript

.secrets.baseline, backend/data_tools/data/user_data.json5, backend/data_tools/src/etl_data_from_excel/import_project_data_from_excel.py, backend/data_tools/src/import_static_data/import_data.py, backend/data_tools/tests/conftest.py, backend/models/users.py, backend/ops_api/Pipfile, backend/ops_api/Pipfile.lock, backend/ops_api/ops/utils/auth.py, backend/ops_api/ops/utils/authorization.py, backend/ops_api/tests/ops/auth/test_utils.py, backend/ops_api/tests/ops/auth_client.py, docs/BLI/create-bli-step-3.mmd, frontend/cypress.config.js, frontend/cypress/e2e/auth.cy.js, frontend/cypress/e2e/canDetail.cy.js, frontend/cypress/e2e/canList.cy.js, frontend/cypress/e2e/portfolioDetail.cy.js, frontend/cypress/e2e/portfolioList.cy.js, frontend/cypress/e2e/utils.js
* Initial take on Authorization Gateway that can take a Authorization Provider
* minor lint/format cleanup
* added `pytest-mock` for use in testing
* added basic AuthorizationGateway unit test
* updated e2e to include better `a11y` logging output on violations.
#753 
* Currently only a framework, unit tests are the only existing tests.
=> OPS-753 AuthorizationGateway

.secrets.baseline, backend/data_tools/Pipfile, backend/data_tools/Pipfile.lock, backend/data_tools/data/research_project_data.json5, backend/models/research_projects.py, backend/ops_api/ops/base_views.py, backend/ops_api/ops/resources/research_projects.py, backend/ops_api/ops/utils/query_helpers.py, backend/ops_api/tests/ops/research_project/test_research_project.py, openapi.yml
Added `search` param to `/research-projects` endpoint.
https://github.com/HHS/OPRE-OPS/issues/735
E2E still works.
=> Ops 735 research projects endpoint

backend/models/base.py, backend/models/events.py, backend/models/users.py, backend/ops_api/ops/environment/local/localhost.py, backend/ops_api/ops/resources/auth.py, backend/ops_api/ops/utils/auth_views.py, backend/ops_api/ops/utils/events.py, backend/ops_api/tests/ops/auth/test_oidc_controller.py, backend/ops_api/tests/ops/users/test_users.py, backend/ops_api/tests/ops/utils/test_events.py
POC Backend Event System.
Addressed some tech debt for auth unit tests.
https://github.com/HHS/OPRE-OPS/issues/750
E2E still works.
=> Ops 750 ops events

frontend/src/pages/budgetLines/CreateBudgetLine.jsx
Added description for budget lines
#743
=> starts description

frontend/src/pages/budgetLines/CreateBudgetLine.jsx
=> Task744 amount

frontend/src/pages/budgetLines/CreateBudgetLine.jsx, frontend/src/pages/budgetLines/DesiredAwardDate.jsx, frontend/src/pages/budgetLines/createBudgetLineSlice.js
Adds memorable date for budget lines
#745 
Add month, day, and year to the budget line and see it show up in state after clicking add budget line button.
=> adds date select

frontend/src/pages/budgetLines/CanSelect.jsx, frontend/src/pages/budgetLines/CreateBudgetLine.jsx, frontend/src/pages/budgetLines/ProjectSelect.jsx, frontend/src/pages/budgetLines/createBudgetLineSlice.js
Adds comments aka notes to BLI
#746
=> Task746 notes

.secrets.baseline, backend/models/__init__.py, backend/models/cans.py, backend/models/history.py, backend/models/portfolios.py, backend/models/research_projects.py, backend/ops_api/ops/__init__.py, backend/ops_api/ops/db.py, backend/ops_api/ops/history.py, backend/ops_api/tests/ops/conftest.py, backend/ops_api/tests/ops/history/test_history.py, frontend/cypress/e2e/canDetail.cy.js
POC DB Data History tracking.
https://github.com/HHS/OPRE-OPS/issues/750
E2E still works.
=> Ops 750 db history poc

backend/data_tools/Pipfile, backend/data_tools/Pipfile.lock, backend/data_tools/data/agreements_and_blin_data.json5, backend/models/base.py, backend/models/procurement_shops.py, backend/ops_api/Pipfile, backend/ops_api/Pipfile.lock, backend/ops_api/ops/base_views.py, backend/ops_api/ops/resources/procurement_shops.py, backend/ops_api/tests/ops/can/test_procurement_shops.py
This finishes the backend code for 725, making the API actually able to be used.
[#725](https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/725)
Pytest validates things are working.
N/A
N/A
=> 725 fixing views

backend/ops_api/ops/base_views.py, backend/ops_api/ops/resources/agreements.py, backend/ops_api/ops/resources/auth.py, backend/ops_api/ops/resources/budget_line_items.py, backend/ops_api/ops/resources/can_fiscal_year.py, backend/ops_api/ops/resources/can_funding_summary.py, backend/ops_api/ops/resources/cans.py, backend/ops_api/ops/resources/portfolio_cans.py, backend/ops_api/ops/resources/portfolio_funding_summary.py, backend/ops_api/ops/resources/research_project_funding_summary.py, backend/ops_api/ops/resources/research_projects.py, backend/ops_api/ops/resources/users.py, backend/ops_api/ops/utils/auth_views.py, backend/ops_api/ops/utils/response.py
Refactor: Add function `make_response_with_headers`
https://github.com/HHS/OPRE-OPS/issues/749
E2E still works.
=> refactor:add make_response_with_headers

.secrets.baseline, backend/models/events.py, backend/models/portfolios.py, backend/models/research_projects.py, backend/models/users.py, backend/ops_api/ops/resources/research_projects.py, backend/ops_api/ops/utils/research_project_helper.py, backend/ops_api/tests/ops/funding_summary/test_research_project_funding_summary.py, backend/ops_api/tests/ops/research_project/test_research_project.py, frontend/cypress/e2e/researchProjectDetail.cy.js, frontend/cypress/fixtures/initial-state.json, frontend/src/components/CANs/CanCard/CanCard.jsx, frontend/src/pages/researchProjects/detail/ResearchProjectDetail.jsx, frontend/src/pages/researchProjects/detail/researchProjectSlice.js, openapi.yml
POST to `/research-projects/`.
New OpsEventType: CREATE_NEW_RESEARCH_PROJECT
Remove Portfolio from ResearchProject DB model.
Bug:Fix intermittent e2e a11y issue with ids.
Bug:Fix `fullname` in User DB model not set correctly.
https://github.com/HHS/OPRE-OPS/issues/849
- Authenticate to the API
- POST to `http://localhost:8080/api/v1/research-projects/` with body:
```
{
"title": "Research Project #1",
"short_title": "RP#1",
"description": "blah blah blah",
"url": "https://example.com",
"origination_date": "2023-01-01",
"methodologies": [
"SURVEY",
"FIELD_RESEARCH",
"PARTICIPANT_OBSERVATION"
],
"populations": [
"POPULATION_1",
"POPULATION_2"
],
"team_leaders": [
{
"id": 1
},
{
"id": 2
},
{
"id": 3
}
]
}
```
- You should get a 201 Response back that looks like this:
```
{
"created_by": 12, …
```
=> Ops 849 post research projects

backend/data_tools/Pipfile.lock, backend/models/cans.py, backend/ops_api/Pipfile.lock, backend/ops_api/ops/resources/agreements.py, backend/ops_api/ops/urls.py, backend/ops_api/ops/views.py, frontend/src/api/getAgreements.js, frontend/src/pages/agreements/AgreementReasonSelect.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/createAgreementSlice.js
Agreement Reasons frontend & backend implemented.
See: [Create Reason for Agreement details #836](https://github.com/HHS/OPRE-OPS/issues/836)
=> Ops 836 create reason for agreement details

backend/models/cans.py, backend/models/procurement_shops.py, backend/ops_api/tests/ops/agreement/test_agreement.py, frontend/src/pages/budgetLines/createBudgetLineSlice.js
- Fixed how the proc_shop and agreement relationships were defined.
=> hotfix_procurement_shop

.github/actions/deploy-backend/action.yml, .github/actions/deploy-data-tools/action.yml, backend/ops_api/ops/utils/auth_views.py, backend/ops_api/pytest.ini
Increased timeout to provision backend services.
Added a couple logging statements to the `/login` endpoint.
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/765
Attempt to log into the DEV env: https://ops-dev.fr.cloud.gov/
=> Ops 765 cannot login

frontend/src/pages/budgetLines/PreviewTable.jsx, frontend/src/pages/budgetLines/TotalSummaryCard.jsx
fixes bugs with fees and formatting
=> fixes fees and formatting issues

frontend/src/pages/budgetLines/CreateBudgetLine.jsx, frontend/src/pages/budgetLines/PreviewTable.jsx
fixes bug on edit budget line and table with currency formatting
=> more currency formatting issues

.secrets.baseline, backend/ops_api/ops/resources/budget_line_items.py, backend/ops_api/tests/ops/can/test_budget_line_item.py, frontend/src/pages/agreements/StepCreateAgreement.jsx, openapi.yml
Update BudgetLineItem (PATCH)
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/674
- Create a new BLI by POSTing to: http://localhost:8080/api/v1/budget-line-items/ with the Request:
```
{
"line_description": "LI 1",
"comments": "hah hah",
"agreement_id": 1,
"can_id": 1,
"amount": 200.24,
"status": "DRAFT",
"date_needed": "2024-01-01",
"psc_fee_amount": 2.34
}
```
You should receive a Response like:
```
{
"agreement_id": 1,
"amount": 200.24,
"can_id": 1,
"comments": "hah hah",
"created_by": 12,
"created_on": "2023-04-19T19:59:15.835202",
"date_needed": "2024-01-01",
"id": 20,
"line_description": "LI 1",
"psc_fee_amount": 2.34,
"status": "DRAFT",
"updated_on": "2023-04-19T19:59:15.835202"
}
```
Note the new BLI id - in this case 20
Update BLI 21 by …
=> Ops 674 patch bli

frontend/src/pages/agreements/AgreementReasonSelect.jsx, frontend/src/pages/agreements/AgreementTypeSelect.jsx, frontend/src/pages/agreements/ProcurementShopSelect.jsx, frontend/src/pages/agreements/ProductServiceCodeSelect.jsx, frontend/src/pages/agreements/ProjectSelect.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/StepCreateBudgetLines.jsx, frontend/src/pages/agreements/StepSelectProject.jsx, frontend/src/pages/agreements/createAgreementSlice.js, frontend/src/pages/budgetLines/CreateBudgetLine.jsx, frontend/src/pages/budgetLines/ProjectSelect.jsx
Project Summary Card
- shows description instead of project lead
- adds PropTypes -adds default export
#775
=> Agreement Flow Frontend Improvements

backend/models/cans.py, backend/ops_api/ops/resources/agreements.py, backend/ops_api/tests/ops/agreement/test_agreement.py, frontend/src/api/postAgreements.js, frontend/src/api/postAgreements.test.js, frontend/src/pages/agreements/ProcurementShopSelect.jsx, frontend/src/pages/agreements/ProductServiceCodeSelect.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/createAgreementSlice.js, frontend/yarn.lock
- Created `postAgreement` function
- Added `notes` to Agreement model
- Created transform function for Redux state to POST object for Agreement
- Added `postAgreement` unit tests
#886 
Unit Tests or Live - /agreements/create - Step 2 `Continue` or `Save Draft` should create a Agreement in DB
=> Ops-886_Wire_POST_Agreement

frontend/src/api/postAgreements.js, frontend/src/api/postBudgetLineItems.js, frontend/src/pages/agreements/AgreementReasonSelect.jsx, frontend/src/pages/agreements/AgreementTypeSelect.jsx, frontend/src/pages/agreements/ProductServiceCodeSelect.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/StepCreateBudgetLines.jsx, frontend/src/pages/agreements/createAgreementSlice.js
- Fixed minor linting issues
- Completed the wiring of the `createAgreement` flow
- `/agreements/create` Now completes successfully!!!! 🎉 
#775
Run it!
=> Patch updated agreement id for post budget line items

frontend/src/pages/agreements/CreateAgreement.jsx, frontend/src/pages/agreements/StepReviewAgreement.jsx, frontend/src/pages/budgetLines/PreviewTable.jsx
adds Agreement Review page
#891 
for now, goto Agreement create steps and this will show as the last step in the wizard
=> adds Agreement Review page

backend/ops_api/ops/resources/agreements.py, frontend/src/pages/agreements/ProcurementShopSelect.jsx, frontend/src/pages/agreements/ProjectSelect.jsx, frontend/src/pages/agreements/createAgreementSlice.js, frontend/src/pages/agreements/list/AgreementTableRow.jsx
- Fixed Bugs:
- #906 
- #907 
#906 
#907
=> PATCH: bug fixes for demo

backend/data_tools/Pipfile.lock, backend/ops_api/Pipfile.lock, backend/ops_api/tests/ops/can/test_budget_line_item.py, backend/ops_api/tests/ops/research_project/test_research_project.py, frontend/src/api/postProjects.js, frontend/src/components/UI/Header/Menu.jsx, frontend/src/index.jsx, frontend/src/pages/agreements/StepSelectProject.jsx, frontend/src/pages/projects/CreateProject.jsx, frontend/src/pages/projects/ProjectTypeSelect.jsx, frontend/src/pages/projects/createProjectSlice.js, frontend/src/store.js
Added "Create Project" page.
[#883 ](https://github.com/HHS/OPRE-OPS/issues/883)
1. Open site & log in.
2. Go to Create Project.
3. Do stuff.
=> Ops 883 create project front end

frontend/src/api/postAgreements.js
Fix bug in Create Agreement page.
https://github.com/HHS/OPRE-OPS/issues/916
You can create an Agreement.
=> Ops 916 fix product service code

frontend/src/pages/agreements/StepSelectProject.jsx
- Wired up the `Add Project` button on Step 1 of `Create Agreement`
=> wired up the Add Project button

frontend/src/pages/agreements/StepCreateBudgetLines.jsx
Reset form state after creating BLIs.
https://github.com/HHS/OPRE-OPS/issues/918
Create more than 1 Agreement.
=> bug:after creating BLIs clear the state

frontend/src/api/opsAPI.js, frontend/src/pages/agreements/ProjectSelect.jsx, frontend/src/pages/agreements/StepSelectProject.jsx, frontend/src/pages/projects/CreateProject.jsx
- Fixed Bug #920 
- Created AddResearchProject Mutation to RTK
- Added getResearchProjects Query to RTK
- Updated loading logic within `ProjectSelect` component
#920 
- Create new project
- Add New Agreement - Project Select should have newly created Project
=> Patch fixed new project select addition

backend/data_tools/data/agreements_and_blin_data.json5, backend/data_tools/data/can_data.json5, backend/ops_api/tests/ops/can/test_can.py
CanSelect data was malformed.
Id was not in correct order.
#924 
Select a new CAN and watch it not break
=> data-fixes

frontend/src/components/UI/Form/CreateBudgetLinesForm.jsx
Fix blank BLI need by date bug.
https://github.com/HHS/OPRE-OPS/issues/898
Follow steps in the issue to attempt to reproduce.
=> bug:blank need by date

frontend/src/pages/agreements/ProjectSelect.jsx, frontend/src/pages/agreements/ReviewAgreement.jsx, frontend/src/pages/projects/CreateProject.jsx
- Removed `{ }` from around the `ProjectSelect` prop `projects`; I think it was left in by mistake during testing.
- Reworked how the CreateProject object was getting the `id` back, post creation
- Cleared CreateProject form after submission
#920
=> Patch create agreement project loading

frontend/package.json, frontend/src/api/opsAPI.js, frontend/src/pages/agreements/list/AgreementsList.jsx, frontend/src/pages/agreements/list/utils.js, frontend/src/pages/agreements/list/utils.test.js
Improve sort order of Agreements List.
Go to `/agreements/`
=> Improve agreement sort order

frontend/src/pages/agreements/list/AgreementsList.jsx
Added auto-refresh of data to Agreement List (on page load).
Create a new agreement and when redirected to Agreement List page the new Agreement appears without refreshing the browser.
=> force refetch

backend/data_tools/data/agreements_and_blin_data.json5, backend/ops_api/README.md, frontend/src/pages/agreements/ProcurementShopSelect.jsx, frontend/src/pages/agreements/ReviewAgreement.jsx, frontend/src/pages/agreements/list/AgreementTableRow.jsx, frontend/src/pages/agreements/list/AgreementTableRow.test.js, frontend/src/pages/budgetLines/PreviewTable.jsx, frontend/src/pages/budgetLines/ProcurementShopSelect.jsx, frontend/src/pages/budgetLines/ProjectAgreementSummaryCard.jsx, frontend/src/pages/budgetLines/ProjectAgreementSummaryCard.test.js, frontend/src/pages/budgetLines/TotalSummaryCard.jsx
- Adjusted the `Procurement_Shop` fee to be a decimal value in the Data / DB
- The intent here is to make it safer for calculations to use the decimal form, instead of relying on a `/ 100` each time it's used.
- Added unit tests for AgreementTableRow
- Updated the displayed Fee on CreateAgreement flow
- Update to Readme, removed unused sections. 
#940 
`yarn test`
=> Ops-940 Proc Shop Fee

backend/data_tools/data/user_data.json5, frontend/src/helpers/utils.js, frontend/src/pages/agreements/list/AgreementTableRow.jsx, frontend/src/pages/agreements/list/AgreementsList.jsx, frontend/src/pages/agreements/list/utils.test.js, frontend/src/pages/budgetLines/PreviewTable.jsx
Fixed bug #947 
Dates were being displayed with Time zone.
1. create budget lines
2. view in agreement list 
3. view in agreement preview
4. dates should match
=> fixes date off by one

frontend/cypress/e2e/createResearchProject.cy.js, frontend/src/components/UI/Alert/Alert.jsx, frontend/src/pages/projects/CreateProject.jsx, frontend/src/pages/projects/ProjectTypeSelect.jsx, frontend/src/pages/projects/createProjectSlice.js
Handle Cancel button on Create Research Project page.
Begin refactoring and adding E2E tests.
https://github.com/HHS/OPRE-OPS/issues/946
While creating a RP click Cancel - a modal will pop up to confirm.
=> Ops 946 cancel research project

frontend/cypress/e2e/createAgreement.cy.js, frontend/src/components/UI/Form/ProjectSelect.jsx, frontend/src/pages/agreements/AgreementReasonSelect.jsx, frontend/src/pages/agreements/AgreementTypeSelect.jsx, frontend/src/pages/agreements/ProductServiceCodeSelect.jsx, frontend/src/pages/agreements/ProjectOfficerSelect.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/StepSelectProject.jsx, frontend/src/pages/agreements/TeamMemberSelect.jsx, frontend/src/pages/budgetLines/ProjectAgreementSummaryCard.jsx
Add Initial E2E Tests for Create Agreement.
Fix a11y issues.
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/775
Test that you can still create an Agreement in OPS.
=> E2e create agreement

frontend/src/pages/budgetLines/PreviewTable.jsx
Fixed logic for the Created By to be displayed correctly.
#934 
1. Start front-end
2. Create an Agreement.
3. Create a Budget Line (or use an existing one).
4. Duplicate the line (with the icon/button).
5. Verify both copies of the budget line have Created By filled out when expanded.
=> OPS-934 - Bug smashed.

docs/adr/019-style-guide-for-frontend-state.md
Tentative ADR for managing frontend state.
=> initial file

frontend/cypress/e2e/createAgreement.cy.js, frontend/src/api/getAgreements.js, frontend/src/api/getProductServiceCodes.js, frontend/src/api/opsAPI.js, frontend/src/api/postAgreements.js, frontend/src/components/ResearchProjects/ProjectSummaryCard/ProjectSummaryCard.jsx, frontend/src/pages/agreements/AgreementTypeSelect.jsx, frontend/src/pages/agreements/ProductServiceCodeSelect.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx
Refactor some Agreement components - round 1
https://github.com/HHS/OPRE-OPS/issues/964
=> Ops 964 refactor agreement round 1

frontend/src/components/UI/Header/Menu.jsx, frontend/src/pages/agreements/StepSelectProject.jsx
Fixes text color 
#994 
Goto create agreement and see new color
=> Ops 994/color fix

frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/StepCreateBudgetLines.jsx, frontend/src/pages/agreements/StepSelectProject.jsx
updates button text
#1006 
Goto create agreement and hit cancel anytime in the workflow
=> updates button text

backend/data_tools/data/user_data.json5, backend/ops_api/ops/base_views.py, frontend/cypress/e2e/createAgreement.cy.js, frontend/src/api/opsAPI.js, frontend/src/components/UI/Form/CreateBudgetLinesForm.jsx, frontend/src/components/UI/Header/User.jsx, frontend/src/helpers/utils.js, frontend/src/pages/budgetLines/PreviewTable.jsx, frontend/src/pages/budgetLines/PreviewTable.test.js
Made User object get loaded with RTK, added some tests around the created_by component to make sure it always has a value in it.
#975 
N/A Bug fix.
N/A
N/A
=> Ops 975 user object fix

frontend/cypress/e2e/components.cy.js
=> writes test for modal

frontend/src/pages/agreements/StepCreateBudgetLines.jsx, frontend/src/pages/budgetLines/ProjectAgreementSummaryCard.jsx
Adds percent sign after zero.
#1019 
Create budget line and with a proc_shop that is zero-based and see the percent sign in the summary card.
=> fixes #1019

backend/models/cans.py, backend/ops_api/ops/resources/agreements.py, backend/ops_api/tests/ops/agreement/test_agreement.py
There was further work needed to make PATCH functional.
#1083
`pytest`
There is a new test to validate the PATCH works.
N/A
N/A
=> Fix patch validation agreements part 2

frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/StepCreateBudgetLines.jsx, frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/index.js, frontend/src/pages/agreements/CreateAgreement.jsx, frontend/src/pages/budgetLines/CreateBudgetLine.jsx
adds dynamic text for create BLIs continue button
#1082 
Create a new agreement and on last step see button text **Save Draft.**
Create budget lines and on last step see button text **Create Budget Lines**.
=> adds dynamic text for create BLIs continue button

docker-compose.debug.yml, docker-compose.e2e.yml, docker-compose.yml
Fix backend container hot reload feature.
Start a local docker dev environment and edit a file in the backend - the change should take effect without having to rebuild the container.
=> fix path to directory in volumes: for backend

backend/models/events.py, backend/ops_api/ops/resources/budget_line_item_schemas.py, backend/ops_api/ops/resources/budget_line_items.py, backend/ops_api/tests/ops/features/test_validate_draft_budget_lines.py, backend/ops_api/tests/ops/features/validate_draft_budget_lines.feature
Added Event for "BLI Send For Approval" action.
https://github.com/HHS/OPRE-OPS/issues/1107
* Log into the app to get an access token
* Use Postman or another similar client to execute the following requests:
```
POST http://localhost:8080/api/v1/budget-line-items/
Content-Type: application/json
Authorization: Bearer ****
{
"agreement_id": 1,
"line_description": "LI 1",
"amount": 100.12,
"can_id": 1,
"date_needed": "2043-04-01",
"psc_fee_amount": 1.23
}
PATCH http://localhost:8080/api/v1/budget-line-items/21
Content-Type: application/json
Authorization: Bearer ****
{
"status": "UNDER_REVIEW"
}
POST http://localhost:8080/api/v1/budget-line-items/
Content-Type: application/json
Authorization: Bearer ****
{
"agreement_id": 1,
"line_description": "LI 1",
"amount": 100.12,
"can_id": 1, …
```
=> Ops 1107 event history send for approval

frontend/src/components/UI/Form/Input/Input.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/stepCreateAgreementSuite.js
starts title validation
enforces title field and disables continue and save draft buttons.
#1115
=> Adds Validation to Draft Agreement

frontend/cypress/e2e/reviewAgreement.cy.js, frontend/src/components/UI/Alert/Alert.jsx, frontend/src/components/UI/Alert/SimpleAlert.jsx, frontend/src/components/UI/PreviewTable/PreviewTable.jsx, frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/context.js, frontend/src/helpers/utils.js, frontend/src/pages/agreements/approve/ApproveAgreement.jsx, frontend/src/pages/agreements/review/ReviewAgreement.jsx, frontend/src/pages/agreements/review/Terms.jsx, frontend/src/pages/agreements/review/index.js, frontend/src/pages/agreements/review/suite.js
- moves Review Agreement into its own folder
- better JSDocs
- starts test suite
- adds SimpleAlert component
#1131 
1. Create an Agreement with bare minimum properties with(or without ) budget lines. 
2. Select the agreement from the Agreement list page.
3. See Alert errors for Agreement properties needed to be completed.
4. See Send to Review button is disabled.
=> adds Validation to Agreements review page

docs/adr/020-form-validation-library-for-frontend.md
adds ADR for form validation
#1060
=> adds ADR for form validation

frontend/cypress/e2e/agreementList.cy.js, frontend/cypress/e2e/createBudgetLine.cy.js, frontend/src/api/opsAPI.js, frontend/src/components/UI/Form/AgreementSelect/AgreementSelect.jsx, frontend/src/components/UI/Form/AgreementSelect/AgreementSelect.test.js, frontend/src/components/UI/Header/User.jsx, frontend/src/pages/agreements/list/AgreementsList.jsx
Display POs full name in card.
Some a11y and test improvements.
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/1042
1. Goto create budget lines
2. Select a project
3. Select an Agreement
4. PO name should be displayed
=> Ops 1042 project officer name

docs/developers/frontend/vest-examples.md
adds some examples of Vest form validation
Best viewed here: 
https://github.com/HHS/OPRE-OPS/blob/2ad56f293ca2a9f3347c6610c2274f1978bce5b8/docs/developers/frontend/vest-examples.md
=> adds some examples of Vest form validation

frontend/src/components/UI/Form/TeamMemberList.jsx
Use USWDS Icon and set custom padding on tag.
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/995
Compare appearance of tags on Create Agreement screen.
=> use uswds icon and set custom padding

openapi.yml
OpenAPI docs added for POST, PUT, PATCH of an Agreement
#856 
Verify with swagger/openapi editor
=> adds openapi docs for POST, PUT, and PATCH of an Agreement

backend/models/events.py, backend/ops_api/ops/resources/auth.py, backend/ops_api/ops/urls.py, backend/ops_api/ops/utils/auth_views.py, backend/ops_api/ops/views.py, frontend/src/api/apiLogin.js, frontend/src/components/Auth/AuthSection.jsx
Logout now has a handler in the backend, which currently just logs that the user logs out.
#1171 
Log in, log out, and then check the events table in the database to see the event is written.
N/A
N/A
=> Ops 1171 backend logout

frontend/cypress/e2e/editAgreement.cy.js, frontend/cypress/e2e/reviewAgreement.cy.js, frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/StepCreateBudgetLines.jsx, frontend/src/pages/agreements/CreateEditAgreement.jsx, frontend/src/pages/agreements/review/ReviewAgreement.jsx
Adds BLI group errors.
#1189 
1. Review an agreement with invalid BLIs.
2. See errors on step 3
=> Ops 1189/budget line errors

frontend/src/components/UI/Form/CreateBudgetLinesForm/CreateBudgetLinesForm.jsx, frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/StepCreateBudgetLines.jsx, frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/index.js, frontend/src/pages/agreements/CreateEditAgreement.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/StepSelectProject.jsx
refactors form mode to isEdit/Review mode
#1216 
- see if unit-tests and e2e tests pass
=> refactors form mode to isEdit/Review mode

backend/models/cans.py, backend/ops_api/ops/resources/agreements.py, backend/ops_api/tests/ops/agreement/test_agreement.py, frontend/cypress/e2e/agreementList.cy.js, frontend/src/pages/agreements/EditAgreement.js, frontend/src/pages/agreements/list/AgreementTableRow.jsx, frontend/src/pages/agreements/list/AgreementTableRow.test.js, frontend/src/pages/agreements/list/AgreementsList.jsx
Removed agreement.status from frontend and backend.
#1183 
pytest & e2e, can also verify by logging in and checking the agreement list to see there is nothing using or showin an agreement-level status.
N/A
=> Ops 1183 remove agreement status

backend/ops_api/ops/resources/budget_line_item_schemas.py
Remove validation check for team members.
Test that you can send a BLI/Agreement to review without team members.
=> remove check for BLI team members

backend/data_tools/data/user_data.json5, backend/ops_api/tests/ops/notification/test_notification.py
Adding @andressacurvelo  back as a user in `data_tools`
N/A
Have @andressacurvelo try logging back in
N/A
N/A
=> Get Andressa back as a user

frontend/cypress/e2e/reviewAgreement.cy.js, frontend/src/components/UI/Form/DesiredAwardDate/DesiredAwardDate.jsx, frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/suite.js, frontend/src/pages/agreements/review/suite.js
grouping of error messages and more consistent styles based on UX review on 7/25/2023.
=> Ops 675/ux feedback 2

frontend/cypress/e2e/reviewAgreement.cy.js
use first day of the month rather than current day
=> fixes e2e test

frontend/cypress/e2e/agreementList.cy.js, frontend/src/pages/agreements/list/AgreementsFilterHeaderSection.jsx
Add Add Agreement button to Agreement List page.
https://github.com/HHS/OPRE-OPS/issues/1295
Visit the Agreement List page.
=> Ops 1295 create agreement button

frontend/src/pages/agreements/list/AgreementsList.jsx
adds dynamic text based on myAgreementsUrl
#1317 
1. Goto the agreements list
2. Click on tab All Agreements  and MyAgreements tabs
=> adds dynamic text based on myAgreementsUrl

frontend/src/pages/Login.jsx
Removal of unneeded, redundant, and repetitive acronyms and references on the login splash page
N/A
N/A
N/A
N/A
=> Eradicating redundancies on login splash page

backend/ops_api/ops/resources/budget_line_items.py, backend/ops_api/tests/ops/can/test_budget_line_item.py
BLIs are changed to DRAFT status when changed with PUT or PATCH.
#1379 
pytests have been adjusted to verify this.
N/A
N/A
=> OPS-1379: PLANNED BLIs are changed to DRAFT whenever they are edited.

frontend/cypress/e2e/reviewAgreement.cy.js, frontend/src/components/UI/Table/Table.js
- can't delete agreement if BLIs are In Review
- check un-disabled send to approval button
- combines tests into one
=> fix review agreement test

backend/data_tools/data/agreements_and_blin_data.json5, backend/ops_api/tests/ops/agreement/test_agreement.py, backend/ops_api/tests/ops/can/test_budget_line_item.py, backend/ops_api/tests/ops/research_project/test_research_project.py, frontend/cypress/e2e/agreementDelete.cy.js
Adds a new contract in sample data with 2 BLs in planned state so that UI review can proceed. 
#1000 
View Agreements list, verify a new contract called `Interoperability Initiatives` shows up with 2 planned BLs
N/A
=> adding a new agreement with only planned budget lines

backend/ops_api/ops/base_views.py, backend/ops_api/ops/environment/default_settings.py, backend/ops_api/ops/utils/auth.py, backend/ops_api/ops/utils/auth_views.py, backend/ops_api/ops/utils/authentication.py
Added changes to the JWT code to add `fresh=True` when the access token is first made, and `fresh=False` when it is refreshed.
#708
Start up the stack, log into the frontend, get the JWT, and decode it. There is a fresh=true in the JWT.
N/A
N/A
=> Ops 708 log out expire inactive session

frontend/src/components/UI/AllBLIRow/AllBLIRow.js, frontend/src/components/UI/AllBudgetLinesTable/AllBudgetLinesTable.js, frontend/src/components/UI/BLIRow/BLIRow.js, frontend/src/components/UI/BudgetLinesTable/BudgetLinesTable.jsx, frontend/src/components/UI/ChangeIcons/ChangeIcons.js, frontend/src/helpers/useAgreements.js, frontend/src/helpers/useBudgetLines.js, frontend/src/pages/agreements/details/AgreementBudgetLines.js, frontend/src/pages/agreements/list/AgreementTableRow.jsx, frontend/src/pages/agreements/list/AgreementTableRow.test.js, frontend/src/pages/agreements/list/AgreementsTable.test.js, frontend/src/pages/agreements/review/ReviewAgreement.jsx, frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
wires up edit budget line from All BudgetLines Table
does not include
- pre-populating the form with the selected BLI
#1352 
1. login as adminUser
2. goto all budgetlines table
3. attempt to edit a budgetline
4. should route you to the agreement detail bli tab in edit mode
5. logout
6. login as basicUser
7. goto all budgetlines table
8. attempt to edit a budgetline
9. it should NOT let you
https://github.com/HHS/OPRE-OPS/assets/4629398/120de2de-3cca-4f5b-b7d5-28228345aa28
- ~~OESA: Dependency rules followed~~
=> Ops 682/task 1352

frontend/src/components/UI/Form/ComboBox/ComboBox.jsx
As per UX Review - Remove hover color effect from combobox
https://github.com/HHS/OPRE-OPS/issues/1356
=> remove hover effect on borderColor

frontend/cypress/e2e/budgetLineItemList.cy.js, frontend/src/components/UI/FilterTags/FilterTags.jsx, frontend/src/pages/budgetLines/list/BLIFilterButton.jsx, frontend/src/pages/budgetLines/list/BLIFilterTags.jsx, frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Add Filter Tags component to BLI List page.
https://github.com/HHS/OPRE-OPS/issues/1357
Navigate to the BLI List page and select some filters - the corresponding tags should appear.
=> Ops 682/task 1357 filter tags

frontend/cypress/e2e/agreementDetailsEdit.cy.js, frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
updates Alert title when Agreement is updated or added
#1452 
1. Start at the Agreement list 
2. Edit agreement
3. See Alert with Agreement Name
4. profit
- ~~OESA: Code refactored for clarity~~
- ~~OESA: Dependency rules followed~~
- ~~90%+ Code coverage achieved~~
=> style: :lipstick: updates Alert title when Agreement is updated or added

frontend/src/pages/budgetLines/list/BLIFilterTags.jsx
Splits BLI filter tags into separate tags (rather than grouping and using commas)
https://github.com/HHS/OPRE-OPS/issues/1357
Add some filters and verify the tags work as expected.
=> split BLI filter tags into separate tags

.github/workflows/dev_deploy.yml, .github/workflows/staging_deploy.yml
* Stopping any auto cloud deployments.
=> Stop Auto Deployments - No Cloud

README.md, docs/adr/022-use-azure.md, docs/adr/023-use-azure-blob-for-file-storage.md, docs/adr/deprecated/002-use-cloud-dot-gov.md, docs/adr/deprecated/007-use-s3-for-document-storage.md
Updating ADRs for recent decisions or changes with the project
N/A
N/A
N/A
=> Brief but timely ADR update

frontend/src/App.jsx, frontend/src/components/UI/Layouts/DefaultLayout/DefaultLayout.js
docs: :bug: updates propTypes for App and DefaultLayout
- removes React warning
- ~~OESA: Dependency rules followed~~
=> docs: :bug: updates propTypes for App and DefaultLayout

frontend/cypress/e2e/editAgreement.cy.js, frontend/src/components/BudgetLineItems/AllBLIRow/AllBLIRow.js, frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/StepCreateBudgetLines.jsx, frontend/src/pages/agreements/details/AgreementBudgetLines.js
redirects user back to budgetlines after editing BLI
#1509
1. Goto budgetlines page
2. edit a BLI
3. make edits and save
4. 🎉 redirect back to budgetlines page
- ~~OESA: Code refactored for clarity~~
- ~~ OESA: Dependency rules followed~~
=> feat: :sparkles: redirects user back to budgetlines after editing BLI

frontend/src/components/BudgetLineItems/AllBLIRow/AllBLIRow.js, frontend/src/components/BudgetLineItems/BLIRow/BLIRow.js
fix: :bug: fixes table row hover
uses JSX expression and passes into slots
issue #1429
=> fix: :bug: fixes table row hover

backend/data_tools/data/agreements_and_blin_data.json5, backend/data_tools/environment/local_migration.py, backend/data_tools/src/etl_data_from_excel/import_project_data_from_excel.py, backend/data_tools/src/import_static_data/import_data.py, backend/data_tools/src/import_static_data/load_db.py, backend/migration/Pipfile, backend/migration/Pipfile.lock, backend/migration/docker-compose.yml, backend/models/cans.py, backend/ops_api/ops/resources/agreements.py, backend/ops_api/ops/utils/fiscal_year.py, backend/ops_api/tests/ops/agreement/test_agreement.py, backend/ops_api/tests/ops/agreement/test_agreement_history.py, backend/ops_api/tests/ops/features/test_delete_agreement.py, backend/ops_api/tests/ops/features/test_edit_agreement_metadata.py, backend/ops_api/tests/ops/features/test_edit_planned_budget_line.py, backend/ops_api/tests/ops/features/test_validate_draft_budget_lines.py, backend/ops_api/tests/ops/funding_summary/test_research_project_funding_summary.py, backend/ops_api/tests/ops/history/test_history.py, backend/ops_api/tests/ops/utils/test_fiscal_year.py, frontend/cypress/e2e/agreementDelete.cy.js, frontend/cypress/e2e/agreementDetailsEdit.cy.js, frontend/cypress/e2e/editAgreement.cy.js, frontend/cypress/e2e/loginPage.cy.js, frontend/cypress/e2e/portfolioDetail.cy.js, frontend/cypress/e2e/reviewAgreement.cy.js, frontend/cypress/fixtures/initial-state.json, frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
Remove `number` field from Agreement.
Add `local-migration` env and Dockerfile for MAPS/OPS testing.
Fixes for tests in new FY.
https://github.com/HHS/OPRE-OPS/issues/1520
=> Ops 1420/task 1520 maps contracts

frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.js, frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.js, frontend/src/components/BudgetLineItems/BLIStatusSummaryCard/BLIStatusSummaryCard.js, frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.helpers.js, frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.js, frontend/src/components/BudgetLineItems/BudgetLinesTable/BudgetLinesTable.jsx, frontend/src/components/UI/Form/DesiredAwardDate/DesiredAwardDate.jsx, frontend/src/components/UI/TableRowExpandable/TableRowExpandable.js, frontend/src/components/UI/TableRowExpandable/table-row.helpers.js, frontend/src/components/UI/TableRowExpandable/table-row.hooks.js, frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
refactor: :recycle: adds tablerow helpers and hooks
and various cleanup and improvements
Issue #1523 
=> refactor: :recycle: adds tablerow helpers and hooks

frontend/src/components/UI/Form/ProcurementShopSelectWithFee/ProcurementShopSelectWithFee.jsx
PRocurement Shop Select had minor error in display after the change to fix all the math. This corrects the error.
N/A
Open the UI, go to where you can select the procurement shop (like on an agreement). Verify that the percentage is correct (in the small footnote under the selection box).
=> Fixing small visual error.

backend/data_tools/data/portfolio_data.json5, backend/models/portfolios.py, backend/ops_api/tests/ops/portfolio/test_division.py, frontend/cypress/e2e/portfolioDetail.cy.js
Some minor changes to Division model and test data.
https://github.com/HHS/OPRE-OPS/issues/1576
=> Ops 1420/task 1576 division initial

frontend/src/components/Agreements/AgreementBLIReviewTable/AgreementBLIReviewTable.js, frontend/src/components/Agreements/AgreementBLIReviewTable/BLIReviewRow.js, frontend/src/components/Agreements/AgreementBLIReviewTable/index.js, frontend/src/components/UI/TableRowExpandable/TableRowExpandable.js, frontend/src/components/UI/TableTag/TableTag.js, frontend/src/pages/agreements/review/ReviewAgreement.helpers.js, frontend/src/pages/agreements/review/ReviewAgreement.helpers.test.js, frontend/src/pages/agreements/review/ReviewAgreement.jsx, frontend/src/pages/agreements/review/reviewAgreement.hooks.js
- feat: ✨ adds AgreementBLIReviewTable
- feat: ✨ adds BLIReviewRow
- feat: ✨ handles state between action accordion and agreement budgetlines table
Does not include
- Table heading checkbox to select all
- e2e test updates
#1558 
1. Goto Agreements list
2. Choose Agreement 1 to review
3. see table row in disabled state
4. select DRAFT TO PLANNED
5. check table items
6. 💰profit
7. ♻️ Repeat for Agreement 9 but check for PLANNED TO EXECUTING
8. 💰💰profit
=> feat: ✨ adds AgreementBLIReviewTable

backend/data_tools/data/can_data.json5, backend/data_tools/data/portfolio_data.json5, backend/models/cans.py, backend/models/portfolios.py, backend/ops_api/tests/ops/portfolio/test_portfolio.py, frontend/cypress/e2e/portfolioDetail.cy.js
Updates per team req doc.
Updated some Division/Portfolio associations.
Added Division Director and Deputy Division Director to Division.
Added non-null `division_id` to Portfolio.
https://github.com/HHS/OPRE-OPS/issues/1576
https://docs.google.com/document/d/165NZTGL3yreqhDzzhAwcr0Hg-eWf1fN3mUfSI0zG0Uw/edit
=> Ops 1420/task 1576 more division updates

terraform/eus/dev/frontend_asa/context.tf, terraform/eus/dev/frontend_asa/main.tf, terraform/eus/dev/frontend_asa/providers.tf, terraform/eus/dev/frontend_asa/terraform.tf, terraform/eus/dev/frontend_asa/variables.tf
=> feat: added terraform module for asa deployment

terraform/eus/dev/frontend_asa/context.tf
=> chore: pointed context to versioned ref

.github/workflows/ci.yml, terraform/global/context/main.tf
=> fix: took out ssh source

frontend/Dockerfile
=> Update Dockerfile again

frontend/Dockerfile
=> chore: Test TF Bun Build

frontend/Dockerfile
=> chore: Pulled latest main for testing.

backend/Dockerfile.ops-api
=> chore: fix gunicorn worker pid

backend/Dockerfile.ops-api
=> chore: Added comment

frontend/index.js
=> chore: Comment index

frontend/index.js
=> chore: added error path

frontend/Dockerfile.azure
=> chore: cleared whitespace

backend/Dockerfile.ops-api
=> chore: Verifying action changes

terraform/eus/dev/data-tools/terraform.tf, terraform/eus/dev/frontend/terraform.tf, terraform/eus/dev/frontend_asa/terraform.tf
Found additional state key issues.
State is still messed up...
=> fix: discoved other state file issues

frontend/src/components/UI/Form/BLIStatusComboBox/BLIStatusComboBox.jsx, frontend/src/components/UI/Form/BLIStatusComboBox/BLIStatusComboBox.test.js, frontend/src/components/UI/PaginationNav/PaginationNav.jsx
- Refactor BLIStatusComboBox and PaginationNav components
- removes IN_REVIEW from BLI filters 
#1874 
1. Goto All Budget Lines list.
2. Goto page 2
3. Apply a filter like DRAFT
4. Should go to page 1
=> Fixes filter bug 

frontend/cypress/e2e/reviewAgreement.cy.js, frontend/src/components/Agreements/AgreementActionAccordion/AgreementActionAccordion.js, frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.js, frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.js, frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.js, frontend/src/pages/agreements/approve/ApproveAgreement.js, frontend/src/pages/agreements/review/ReviewAgreement.jsx
UX Review fixes from UX Feedback on 1/18/2024.
#1889 
=> UX Review fixes

frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.js
adds placeholder tags for Cans outside of division
#677 
1. Goto Agreement approve page and see Tags for Cans Outside your division
2. 💰profit
=> adds placeholder tags for Cans outside of division

terraform/eus/dev/frontend_asa/build_bun/context.tf
Fixed another module path... removed pinned version that renovate modified.
Builds still breaking on module download.
=> fix: another renovate fix

backend/data_tools/environment/azure.py
Took out the url encoding. Don't believe it will be necessary. 
Data-tools getting errors on the password, cannot connect to db.
=> fix: Update connections string

backend/data_tools/data/agreements_and_blin_data.json5, backend/data_tools/data/first_contract_data.json5, backend/models/cans.py, backend/ops_api/tests/ops/agreement/test_agreement.py, backend/ops_api/tests/ops/features/test_delete_agreement.py, backend/ops_api/tests/ops/features/test_edit_agreement_metadata.py, backend/ops_api/tests/ops/features/test_edit_planned_budget_line.py, backend/ops_api/tests/ops/features/test_validate_draft_budget_lines.py, backend/ops_api/tests/ops/features/test_validate_draft_budget_lines_in_workflow.py, frontend/src/helpers/utils.js
Contract Type Enum with new values for 
- Firm Fixed Price (FFP)
- Time & Materials (T&M)
- Labor Hour (LH)
- Cost Plus Fixed Fee (CPFF)
- Cost Plus Award Fee (CPAF)
- Hybrid (Any combination of the above)
#1944 #1852 
run tests
https://flexion.slack.com/archives/C055PQWCCJ2/p1707367487701899?thread_ts=1707340286.631859&cid=C055PQWCCJ2
=> OPS-1944 Contract Type (backend)

openapi.yml
adds OpenAPI docs for services-components
#1852 
#2023 
view the docs
=> OPS-1852/task-2023 OpenAPI docs for services-components

backend/ops_api/ops/resources/budget_line_items.py, backend/ops_api/ops/resources/procurement_steps.py, backend/ops_api/ops/resources/services_component.py, backend/ops_api/ops/utils/api_helpers.py, backend/ops_api/tests/ops/can/test_services_component.py
* FIX: handle null dates in services components and procurement steps
* make it a little DRYer (along with similar lines in BLIs)
#2039 
run the tests (now includes a PATCH with a null date)
=> fix: handle null dates in services components

frontend/cypress/e2e/agreementDetails.cy.js, frontend/cypress/e2e/createAgreement.cy.js, frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx, frontend/src/components/Agreements/DetailsTabs/DetailsTabs.jsx, frontend/src/components/Agreements/ProductServiceCodeSelect.jsx, frontend/src/components/UI/WizardSteps/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx, frontend/src/components/UI/WizardSteps/CreateBLIsAndSCs/createBLIsAndSCs.hooks.js
- Fixes Cancel logix
#1932 
1. Goto Agreement details page
2. enter edit mode
3. cancel
4. 🔴 should not delete Agreement
5. same as above but on Budget Lines tab
=> Ops 1932/Cancel Logix bug

frontend/src/pages/agreements/approve/ApproveAgreement.js
Improved the approver success alert to include what status change was approved and to which agreement
- Dev did not match figma design
- Previously said: "Approval Saved. The approval to change budget lines was saved."
- Changed to "Budget Lines Approved for Executing Status. Budget lines for Agreement “Title” have been successfully approved for Executing Status."
N/A
- Login in as DD or Admin User
- Go to approval for an agreement
- Approve the status change request
- View success alert with content changes
This is the design in Figma, but simplified a bit to remove the detail about Procurement Process and Notes. These can be added later, but for now we can keep the alerts more global.
_If relevant, e.g. for a link to a piece of markdown …
=> Content change for approver success alert

backend/ops_api/Pipfile.lock
=> update lock file

.github/workflows/dev_be_build_and_deploy.yml, .github/workflows/dev_fe_build_and_deploy.yml
Added hash to azure login for v2.1.0
Needed to use azure login v2
=> chore: using hash for azure login

docs/developers/onboarding.md
Starts onboarding template with areas for frontend, backend, devops, etc.
#2141 
- [-] Automated unit tests updated and passed
- [-] Automated integration tests updated and passed
- [-] Automated quality tests updated and passed
- [-] Automated load tests updated and passed
- [-] Automated a11y tests updated and passed
- [-] Automated security tests updated and passed
- [-] 90%+ Code coverage achieved
=> feat: starts onboarding template

frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx, frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.hooks.js, frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.jsx, frontend/src/components/UI/FilterTags/FilterTagsWrapper.jsx, frontend/src/pages/agreements/CreateEditAgreement.jsx, frontend/src/pages/agreements/StepCreateAgreement.jsx, frontend/src/pages/agreements/StepSelectProject.jsx, frontend/src/pages/budgetLines/BudgetLineContext.hooks.js, frontend/src/pages/budgetLines/BudgetLineContext.jsx, frontend/src/pages/budgetLines/CreateBudgetLine.jsx, frontend/src/pages/budgetLines/StepSelectProjectAndAgreement.jsx, frontend/src/pages/budgetLines/index.jsx, frontend/vite.config.mjs
- missed a few React components
- fixes vite warnings about React Context providers
=> chore: Update jsx extensions and clean up code

README.md, frontend/package.json
updates docs and script for vitest coverage
`bun run test:coverage`
https://vitest.dev/guide/coverage
=> docs: updates docs and script for vitest coverage

backend/ops_api/Pipfile, backend/ops_api/Pipfile.lock
Upgrade to flask v3
Tests pass.
- ~[ ] OESA: Code refactored for clarity~
- ~[ ] OESA: Dependency rules followed~
- ~[ ] 90%+ Code coverage achieved~
- ~[ ] Form validations updated~
=> major upgrade flask to v3

frontend/src/pages/Login.jsx
-improvements to the Login page
1. Tests pass
=> feat: ✨ Login page improvements

.github/renovate.json, backend/Dockerfile.data-tools, backend/Dockerfile.data-tools-import, backend/Dockerfile.debug, backend/Dockerfile.ops-api, backend/ops_api/ops/environment/azure/dev.py, backend/ops_api/ops/environment/azure/stg.py
Bug in Azure related to incorrect login.gov config.
=> Azure bug - logingov config incorrect

backend/ops_api/ops/auth/service.py
Fix for bug in Azure with user sessions.
=> change user session check to use header X-Forwarded-For

frontend/src/components/Agreements/Documents/DocumentView.jsx
docs: Update DocumentView propTypes
=> docs: Update DocumentView propTypes

frontend/eslint.config.js
Add Cypress plugin configuration
#1249 
(https://github.com/cypress-io/eslint-plugin-cypress/blob/master/FLAT-CONFIG.md)
=> chore: Add Cypress plugin configuration

backend/ops_api/ops/__init__.py, backend/ops_api/ops/document/__init__.py, backend/ops_api/ops/document/api.py
- Create a Flask blueprint module within the Documents directory (instead of within the API file)
- Update the reference used in the app's blueprint registration 
- Update the blueprint decorator used in the documents route definition  
[Upload a document #2365](https://github.com/HHS/OPRE-OPS/issues/2365)
Unit tests are passing. 
<del>- [ ] Automated a11y tests updated and passed <del>
<del> - [ ] Form validations updated <del>
Links to prior PRs:
1. https://github.com/HHS/OPRE-OPS/pull/2406
2. https://github.com/HHS/OPRE-OPS/pull/2523
=> Revise the document module for clarity.

frontend/src/components/Agreements/AgreementSelect/AgreementSelect.jsx, frontend/src/components/Agreements/AgreementSelect/AgreementSelect.test.js, frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js, frontend/src/components/UI/Header/Menu.jsx, frontend/src/helpers/budgetLines.helpers.js, frontend/src/index.jsx
- fixes UX review issues and bugs identified on 7/9/24
#2546 #2545
=> fix: UX Review fixes

frontend/src/components/Agreements/AgreementDetails/AgreementHistoryList.jsx, frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.jsx, frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.test.jsx, frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx, frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.test.jsx
- addresses UX Review items found on JUL 9 2024
- changeTo column consistency in reviewcards
- view all label for link text
#2349 
- watch e2e tests pass
=> fix: 💅 Ops 2349/ux review items

frontend/cypress/e2e/budgetChangeRequest.cy.js, frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js, frontend/src/pages/agreements/details/AgreementBudgetLines.jsx, frontend/src/pages/agreements/details/AgreementDetails.test.js
- Modify the showSuccessMessage function in CreateBLIsAndSCs.hooks.js to include a flag indicating if there are any financial snapshot changes. If there are changes, display a success message with a redirect URL to the agreement details page. Otherwise, display a generic success message.
Does not include
- change request messages in the Alert
#2487
1. Make a Budget Change on Agreement 9 any budget lines
2. save changes and sent to approval
3. see correct Alert message
4. 💰profit
https://github.com/user-attachments/assets/c7096e42-06fc-4386-9de8-a17af4fbef7e
- https://github.com/HHS/OPRE-OPS/pull/2479
=> refactor: Update success Alert for Budget Changes

README.md, docs/developers/onboarding.md
Small edits to project readme and onboarding file. 
Related to https://github.com/HHS/OPRE-OPS/issues/2693
Not applicable
Not applicable
<del> - [ ] OESA: Code refactored for clarity 
<del> - [ ] OESA: Dependency rules followed
<del> - [ ] 90%+ Code coverage achieved
<del> - [ ] Form validations updated
None
=> Tiny edits to project docs

docs/adr/018-use-homegrown-authz.md
Updated the author ADR to relect current/accurate info on the stance of our authorization provider for OPS
🤷 Maybe it should have been done as part of #1146 
N/A
N/A
=> Updating authz ADR

.github/workflows/prod_be_build_and_deploy.yml, .github/workflows/prod_fe_build_and_deploy.yml
Changed workflow name
I accidentally copied the same pipeline name from staging.
=> chore: updated workflow name

backend/data_tools/data/user_data.json5
Adding a user for non-prod environments for our assigned ISSE. No OIDC ID specified until we know what it is.
N/A
Have the user attempt to log in
=> adding ISSE user

docs/adr/027-pki-management.md
Adding an ADR to document our PKI management practices
#2802 
N/A
N/A
=> initial ADR for PKI management

frontend/src/pages/Login.jsx
Remove link to temp auth debugging page.
https://github.com/HHS/OPRE-OPS/issues/2737
=> remove link to auth debugging page

frontend/src/components/CANs/CANFYBudgetRangeSlider/CANFYBudgetRangeSlider.jsx, frontend/src/components/UI/DoubleRangeSlider/DoubleRangeSlider.jsx, frontend/src/components/UI/DoubleRangeSlider/index.js
https://github.com/user-attachments/assets/8c720502-5d09-40ac-a454-ebabc4076797
=> refactor: adds handleChange logix

backend/data_tools/scripts/initial_data.sh, backend/ops_api/ops/utils/health_check.py
Everyone loves a good well-functioning health check?!  right?!!?
* Updates the health check endpoint to look at AMS now instead of login.gov as the azure environments rightly have no specification for login.gov in `AUTHLIB_OAUTH_CLIENTS` 
* Corrects a super-minor user console message for the `initial_data` script
N/A. Ran across it while doing something else. Leave code cleaner than you found it!
Hit up /api/v1/health/ of your favorite azure environment once merged
=> Updating health check criteria and minor errata

.github/workflows/release.yml
Workflow did not have `bun` available - use the `setup-javascript` action instead
=> build: re-use setup-javascript

backend/openapi.yml, backend/ops_api/ops/resources/can_funding_summary.py, backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py, frontend/src/api/opsAPI.js, frontend/src/components/CANs/CANTable/CANTableRow.jsx, frontend/src/pages/cans/list/CanList.jsx
=> chore: integrate can-funding-summary endpoint

backend/ops_api/ops/resources/can_funding_summary.py, backend/ops_api/ops/utils/cans.py, backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py, frontend/src/api/opsAPI.js, frontend/src/pages/cans/list/CanList.jsx
Frontend
-  fix FE url extra encoded space
- handle multiple filter options 
Backend
- refactor main api logic 
- add fiscal year as filter option
=> wip: api integration with frontend can pages

frontend/src/components/Agreements/AgreementDetailsCards/BLIsByFYSummaryCard/BLIsByFYSummaryCard.jsx, frontend/src/components/CANs/CANFundingCard/CANFundingCard.jsx, frontend/src/components/UI/DataViz/LineGraph/LineGraph.jsx
=> refactor: ♻️ use new components

backend/openapi.yml
Updates the server URL specifications found in the openapi.yml file to account for Azure environments and with correct pathing
None, was looking through the API spec for something else and noticed it at the top of the file. To quote our TWA: 
> Leave code cleaner than you found it.
N/A
N/A
=> chore: updating openapi's URLs

backend/data_tools/data/user_data.json5, backend/ops_api/ops/auth/authentication_provider/fake_auth_provider.py, frontend/cypress/support/e2e.js, frontend/src/components/Auth/MultiAuthSection.jsx, frontend/src/components/Users/UserInfo/UserInfo.test.js, frontend/src/constants.js, frontend/src/tests/data.js
- Add the Procurement Team role and test user
https://github.com/HHS/OPRE-OPS/issues/3111
=> Ops 3111/add procurement team role

backend/data_tools/data/user_data.json5, backend/ops_api/tests/ops/users/test_users_get.py, frontend/cypress/e2e/agreementList.cy.js
Fix to avoid duplicate users when importing users from spreadsheet.
=> fix: update user test data with ids

frontend/cypress/e2e/canDetail.cy.js
Merging into feature branch e2e collab branch.
#3098 
#310 
N/A
N//A
N/A
=> test: add can edit form e2e tests

frontend/src/components/CANs/CANDetailView/CANDetailView.jsx, frontend/src/components/CANs/CANHistoryPanel/CANHistoryPanel.jsx, frontend/src/pages/cans/detail/CanDetail.jsx
Enabling infinite scroll in can history. Need to fix a undefined error in InfiniteScroll line 11.
=> feat: wip, enable infinite scroll

frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js, frontend/src/pages/agreements/approve/ApproveAgreement.jsx
=> chore: debug code

frontend/src/index.jsx, frontend/src/pages/cans/list/CanList.jsx
removed feature flag from cans
#310
=> chore: removed feature flag from cans

frontend/src/components/CANs/CANFundingInfoCard/CANFundingInfoCard.jsx
Changed FY to Appropriation FY
Changed FY label to Appropriation FY
#3315 
- Navigate to CAN details
- Click CAN Funding Tab
- View CAN Funding Info
=> refactor: update label

backend/ops_api/ops/__init__.py, backend/ops_api/ops/db.py, backend/ops_api/ops/environment/azure/dev.py, backend/ops_api/ops/environment/azure/prod.py, backend/ops_api/ops/environment/azure/stg.py
Enable SQLAlchemy echo feature in Azure DEV to enable SQL timing/troubleshooting for the login delay issues.
=> feat: enable sqlalchemy echo in DEV

frontend/src/api/opsAPI.js, frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx, frontend/src/errorMiddleware.js, frontend/src/errorMiddleware.test.js
Fix idle session logout and infinite request loop.
https://github.com/HHS/OPRE-OPS/issues/3436
Try to reproduce issue.  Experiment with the timeout settings, etc.
=> fix: bug in reset api; improve NotificationCenter.jsx

frontend/cypress/e2e/canList.cy.js, frontend/src/components/CANs/CANTable/CANTable.jsx, frontend/src/components/CANs/CANTable/CANTableRow.jsx
- fixes #3464
same steps as #3464
- <del>[ ] Form validations updated
=> fix: fixes CANList and CANTable mismatch bug

frontend/cypress/e2e/budgetLineItemsList.cy.js, frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Removed the button to add a new budget line on the list of BLs. See linked issue for more details. 
#3476 
=> Removing add BL button on BL list

backend/ops_api/tests/ops/can/test_can_funding_budget.py
Add small changes to backend unit tests to create and update budgets.
=> test: update budget backend unittests

frontend/src/components/UI/Header/Header.jsx
Finally removes the non-functional search component until such time as it becomes functional
#3507 
Log in and view the search component gone
=> Removing non-functioning search box component

frontend/src/components/Portfolios/PortfolioBudgetSummary/PortfolioBudgetSummary.jsx, frontend/src/components/Portfolios/PortfolioFunding/PortfolioFunding.jsx, frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.jsx, frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
- fixes #3534 
- [-] 90%+ Code coverage achieved
=> refactor: updates data for cards

frontend/cypress/e2e/helpCenter.cy.js, frontend/src/pages/help/Feedback.jsx, frontend/src/pages/help/Feedback.test.jsx, frontend/src/pages/help/Glossary.jsx, frontend/src/pages/help/HowToGuides.jsx, frontend/src/pages/help/HowToGuides.test.jsx
Added contract type to the glossary
#3320 
#3553
navigate to help center
click glossary
view contract type
=> doc: update glossary

frontend/src/components/CANs/CANTable/CANTableHead.jsx
- fixes Tooltip font and spacing in the CANs table
#3503 
1. goto CANs List and hover over table headings Funding Received and Available Budget
=> feat: enhance CAN table header tooltips and styling

frontend/src/pages/help/HowToGuides.jsx
Updating How-to guides text and formatting
#3320 
=> docs: update howtoguides.jsx

frontend/src/api/opsAPI.js, frontend/src/components/CANs/CANTable/CANTable.jsx, frontend/src/utils/tableExport.js
adds the ability to handle paginated data from table 🫠
=> feat: adds helper function based on papaParse

frontend/src/components/UI/DataViz/ResponsiveDonutWithInnerPercent/ResponsiveDonutWithInnerPercent.jsx
fixed donut chart double percent bug
fixes #3597 
Refer to #3597
=> fix: fixed donut chart percent bug

frontend/src/components/ErrorBoundary/ErrorBoundary.jsx, frontend/src/components/ErrorBoundary/TestErrorComponent.jsx, frontend/src/components/ErrorBoundary/index.js, frontend/src/index.jsx, frontend/src/pages/ErrorPage.jsx
1. wraps App in an Error Boundary so that any errors in the child components will be redirected to the ErrorPage offering assistance to the user.
#3466 #1262 #3379 
1. Add the `TestErrorComponent` anywhere in the app
1. see error boundary in effect
[React Error Boundary docs](https://legacy.reactjs.org/docs/error-boundaries.html)
=> feat: adds Error Boundary

frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
- simplify permission check for approver to see ApproveAgreement page
- #3652 #3658
1. in staging, send some StatusChange for approval
2. login as Division Director Dave
3. goto Agreements for Review tab
4. select View All from ChangeRequestCard
5. see ReviewAgreement page
=> refactor: simplify review agreement validation

backend/ops_api/ops/auth/utils.py
- Update user email matching to be case insensitive.
=> fix: update user retrieval logic to use case-insensitive email matching

frontend/src/helpers/agreement.helpers.js
Fixed bug that banner not showing up for non-contract agreement in production.
Viewing any non-contract agreement should show the banner.
=> fix: banner not showing up for non-contract agreement in prod

.github/workflows/dev_be_build_and_deploy.yml, .github/workflows/prod_be_build_and_deploy.yml, .github/workflows/stg_be_build_and_deploy.yml
Sets an environment-specific tag on the `data-tools` container in addition to the tag with its sha image. 
came up when reviewing logs and as part of the automation/IaC parts of #3590 
=> Set environment-specific tag on data-tools container

backend/ops_api/ops/auth/service.py, backend/ops_api/ops/auth/utils.py
Add DB lock to `/refresh` access token checking
https://github.com/HHS/OPRE-OPS/issues/3758
1. Log in using PIV
2. Interact with the application for 30 min
3. The UI will send multiple requests to `/refresh` - each response should be the same
4. The `access_token` in the response should match the `access_token` in the `UserSession` table
=> fix: improve user session handling and token refresh logic

frontend/src/pages/help/FAQ.jsx
Edits and additions to the Help Center FAQs.
=> docs: update faq.jsx

frontend/nginx.conf
Removes the advertisement of the HTTP server version from the HTTP response sent back to a client. 
Remediates a ZAP finding for rule 10036
=> feat(security): hides leaky web server info

frontend/src/App.jsx, frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx, frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js, frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx, frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.jsx, frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx, frontend/src/components/CANs/CANDetailForm/CANDetailForm.hooks.js, frontend/src/components/CANs/CANDetailForm/CANDetailForm.jsx, frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTable.jsx, frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTableRow.jsx, frontend/src/helpers/scrollToTop.helper.js, frontend/src/hooks/useScrollToTop.js, frontend/src/pages/cans/detail/CanFunding.hooks.js, frontend/src/pages/cans/detail/CanFunding.jsx
This PR implements an app-wide scroll-to-top feature and updates various component JSDoc annotations and type definitions for improved consistency and clarity. Key changes include:
- Adding new scroll-to-top helper functions and hook integrations.
- Updating return types in JSDoc from JSX.Element to React.ReactElement.
- Adjusting type annotations (e.g. changing funding and fiscalYear types from string to number) and cleaning up unused URL query param logic.
- closes #3676 
refer to tests on 3676
=> feat: ✨ App-wide scroll to top

backend/openapi.yml, backend/ops_api/ops/resources/agreements.py, backend/ops_api/ops/schemas/agreements.py, backend/ops_api/tests/ops/agreement/test_agreement.py, frontend/cypress/e2e/agreementList.cy.js, frontend/src/pages/agreements/list/AgreementsList.jsx
Updated the agreements endpoint onlyMy filter to allow DDs and Team Leaders
- closes #3786 
1. e2e test pass
2. login as system owner
3. go to /agreements
4. click on the My Agreements tab
=> OPS-3786: allow DDs and Team Leaders in agreements onlyMy filter

.github/workflows/nightly_scans.yml
Corrects a frustrating typo. I blame autocorrect somewhere. Possibly it may have been human error too... 👀 
N/A
Manually invoke nightly security GHA workflow
=> Death by one silly typo / paper cut

frontend/src/pages/cans/list/CanList.helpers.test.js
Adding FE unit tests to filterCANsByFiscalYear
=> test: add unit tests for filterCANsByFiscalYear function

frontend/src/components/Layouts/DefaultLayout/DefaultLayout.jsx
Updating date when we last received data to import
#3967
Log in and look at the top banner...
=> Updating date when we last received data to import 📆💅🏼

frontend/src/components/Layouts/DefaultLayout/DefaultLayout.jsx, frontend/src/constants.js, frontend/src/pages/home/release-notes/ReleaseNotes.test.jsx, frontend/src/pages/home/release-notes/ReleaseNotesCards.jsx, frontend/src/pages/home/release-notes/ReleaseNotesCards.test.jsx
adds constant for LAST_DATA_UPDATE to use anywhere in the app.
1. 🧪 e2e tests pass
=> feat: ✨adds last data update

backend/data_tools/src/disable_users/disable_users.py
* Refactored the conditional logic for determining what users to disable as part of the automation that handles that to include one additional scenario without harming the other two whilst also increasing readability. 
#4075
N/A
=> Update logic used for determining stale users to disable

frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.jsx, frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js, frontend/src/pages/agreements/approve/ApproveAgreement.jsx
Added new awarding entity to AgreementMetaAccordion
=> feat: add new awarding entity to AgreementMetaAccordion

docs/developers/creating-new-users.md
• Add comprehensive documentation for creating new users and roles in OPS  
• Based on real implementation example (PR #4256 SUPER_USER role) to provide practical guidance
• closes #4228 
This documentation analyzes PR #4256 (which added the SUPER_USER role) to provide developers with a complete step-by-step guide for creating new users with specific roles in the OPRE OPS system.
The guide covers:
- Backend changes (5 files): Role definition, authentication, environment configuration
- Frontend changes (8 files): UI components, constants, mock data, testing  
- Step-by-step implementation process
- Important notes and best practices
This will help developers understand the full scope of changes needed when adding new user types and reduce implementation complexity.
=> docs: 📚 add comprehensive guide for creating new users in OPS

frontend/src/components/ServicesComponents/ServicesComponents.constants.js, frontend/src/pages/agreements/agreements.constants.js, frontend/src/types/AgreementTypes.d.ts
Removes frontend references to `IAA_AA` replacing with `AA`
N/A
tests pass
=> cleanup frontend references to IAA_AA

frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Since columns have shifted around, updating the specified columns that currency formatting is used on
#4273 
export some BLs, check the FY column.
=> Updating the columns currency formatting is on for BL exports

frontend/cypress/e2e/editBudgetLineByPowerUser.cy.js
- **test: adds e2e test for aa agreement**
- closes #4299
- depends on https://github.com/HHS/OPRE-OPS/pull/4292
=> feat: ✨su edit aa bli amounts

frontend/src/constants.js
Date of last data submission that was processed
#4387
=> Updating data constant yet again

frontend/src/constants.js
Updates frontend constant for the date of the last data submission that was processed. 
#4434
=> Updating date of last BL submission that was processed

backend/data_tools/src/update_agreement_history/update_agreement_history.py, backend/models/agreement_history.py
Some None-type objects from DB (item not found, basically) lead to a null pointer in code being referenced by script. Fixing this by always having fallback when checking business models instead of just a simple string/number
1. Run unit tests
=> Fixes for Agreement History Conversion in Prod

backend/models/agreement_history.py
Noticed other null pointer issues with null proc shop in agreement history. Fixed this. 
x
1. Run tests
=> fix: fixing other null pointer issues

frontend/src/constants.js
frontend constant of date of last processed submission
#4456
=> Updating frontend constant of date of last processed submission
