- .github/ISSUE_TEMPLATE/generic-issue-template.md
Expected that we may create different templates for feature work, bugs, etc.
> Add GH issue template to standardize the info we include on cards

- docs/how_we_work.md
Added "Engineering Team roles" section to `how_we_work.md`
@amymok @alexsoble I wasn't sure exactly what to put under the "Tech Lead role" subheading. Very open to suggestions there! Especially, would love your feedback @amymok since you're the Tech Lead after all :)
Linked issue #56 
https://github.com/18F/OPRE-Unicorn/blob/0061fa980d01d800f278cb360c14465c945d8d91/docs/how_we_work.md
> Establish Engineering Team roles

- docs/adr/009-use-github-dependabot-and-codeql.md
Resolves #36.
[Preview link.](https://github.com/18F/OPRE-Unicorn/blob/ars/36/adr-for-security-tools/docs/adr/009-use-github-dependabot-and-codeql.md) 👁️
> Add ADR for third-party security tools

- .gitattributes
+ https://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes-file
+ https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more
+ https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
+ https://git-scm.com/docs/gitattributes
+ Closes #52.
Hmmm, how best to review this one? A very rigorous review would involve messing with line endings on your local machine and verifying that the `.gitattributes` enforces the right line endings, I guess? But that would probably be overkill. 
The overall idea here is that having `.gitattributes` up front sets us up for success if/when a developer with a Windows machine [a partner tech lead??] joins us down the line. 
So in my mind, "this looks like a …
> Create .gitattributes for better compatibility with Windows-based devs

- requirements.txt
Removes a package added to the `requirements.txt` as a test for dependabot.
> Remove keras package for dependabot validation

- Dockerfile
- docker-compose.yml
- opre_ops/wait-for-postgres.sh
Modify our use of docker-compose `depends_on` to set up an order for our services' dependences: 
`db` > `migration` > `data` > `web` 
https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on
When I run `docker-compose up` with this config locally, I see the services start in the right order.
> Modify docker-compose depends_on steps to prevent race condition

- opre_ops/ops_site/admin.py
Adds comma separated display of roles for Person in Django Admin.
**note**: could not figure out an elegant/easy way to display the roles on newlines. I tried using `"\n"` in the string builder in the `show_roles()` function as well as injecting `html` using the django `linebreaks()` function and neither produced desired results. 
I landed on comma separation (see below) but open to other's thoughts about how best to proceed.
> Add comma separated display of roles in django admin

- .circleci/config.yml
- manifest.yml
Specified memory for deployment in manifest.yml and used a lighter-weight push command
addressing the error "app requested more memory than available"
By deploying with CircleCI
> Specify memory, don't use zero-downtime-push

- opre_ops/opre_ops/settings/cloudgov.py
Set CSRF_TRUSTED_ORIGINS to a value of the URL at which we deploy the prototype
To fix the error `CSRF verification failed. Request aborted.`
Test by logging in to the deployed environment
> Add CSRF_TRUSTED_ORIGINS to hopefully fix deployment login

- opre_ops/opre_ops/settings/common.py
- opre_ops/opre_ops/settings/static/.gitignore
Two modifications suggested to fix CSS/JS assets not showing up in the admin interface:
1. adding a (nearly) empty `static` directory
2. using a relative path (`static/`) instead of absolute (`/static/`) for the STATIC_URL
The CSS in the Django admin interface is visibly broken, and the links to assets return 404
Deploy and look at the [admin interface](https://opre-ops-test.app.cloud.gov/admin) to see if the CSS works
> Add static directory and use relative pathname

- opre_ops/opre_ops/settings/common.py
Remove unneeded/unsuccessful experiments in prototype deployment
* Running `collectstatic` should produce output like `128 static files copied to '/opre_project/opre_ops/static'`
* Output should not contain `settings` in the path
* Deployed prototype should have working CSS and JS static assets
> Remove deployment experiments

- opre_ops/opre_ops/urls.py
- opre_ops/ops_site/urls.py
- opre_ops/ops_site/views.py
Create a home page, the first view in the prototype app aside from admin views. Create and include a URLconf (`ops_site/urls.py`) for prototype views.
Visit `/ops/home` and see a bare-bones landing page
> Create first view, a home page placeholder

- README.md
There was a broken link in the README. Also, we figured it might be handy to know how we got the fixture data into the database since, presumably, that'll be a useful thing to be able to do at some point. And as is always the case with Python, there's the *system* version, which you do not want to use, and your environment version, which you do, and Cloud Foundry politely defaults to the system version for SSH shells until you tell it otherwise. So... that's documented here for future reference.
> Update README with a fixed link and info about loading fixture data

- .github/renovate.json
- Dockerfile
Renovate now will not automatically merge Python updates.  It requires more than just the one file that Renovate updates to update Python in this project.  The PR will still be created, but we can keep it from merging, improve it, and merge it manually ourselves when we're ready.
#304
> 304: Slow Renovate's Python Updates

- .github/ISSUE_TEMPLATE/feature_work_template.md
- .github/pull_request_template.md
- Typo in the label/metadata for PR templates
- Converting from CoA to AC terminology, because, frankly, I just think it's better. 😀  I welcome diverse viewpoints though.
N/A
N/A
N/A
N/A
> Minor change to GH templates

- .pre-commit-config.yaml
- Added the frontend linting to the pre-commit hooks.
- Removed the Black formatting from the pre-commit hooks because a) it will actually change your file formatting, and b) the backend linting will already fail if there is a Black formatting issue.
#304
`pre-commit run --all-files`
> 304: More Pre-commit Hooks

- .pre-commit-config.yaml
Added pipfile.lock to the exclude list for `detect-secrets`
#304
> ignore pipfile.lock on secrets scanning

- .github/renovate.json
Because Renovate doesn't update all the correct things for Python, and I rather wait until `brew` update its Python package, I want to disable Renovate updating Python.
#304
> 304: Disable Python Updates by Renovate

- README.md
README update to reflect that Django got auto-updated in PR #359 and thusly maybe it's not super-wise to mention specific minor versions in the documentation.
Every time a README goes out of date, we lament. And then update it.
> Remove Django minor version specification in README

- frontend/cypress/e2e/spec.cy.js
Removed the outer describe blocks from the Cypress tests
#304.
`yarn test:e2e` still passes and runs all four tests.
> 304: Remove the outer describe blocks from the Cypress tests

- frontend/Dockerfile
Remove the duplicate `WORKDIR` from the frontend `Dockerfile`.
> Remove duplicate WORKDIR in frontend Dockerfile

- frontend/src/App.jsx
- frontend/src/index.jsx
- frontend/src/pages/portfolios/list/PortfolioList.jsx
- frontend/src/pages/portfolios/list/getPortfolioList.js
- frontend/src/pages/portfolios/list/getPortfolioList.test.js
- frontend/src/pages/portfolios/list/portfolioListSlice.js
- frontend/src/store.js
- Added a dev view to see the list of portfolios.
- This added a unit test and some state.
- A link on the front page to the list.
#376.
`docker compose up` and navigate to http://localhost:3000/
> 376: Dumb Portfolio List View

- frontend/package.json
- frontend/yarn.lock
#391 is failing due ESLint not knowing what version of `eslint-plugin-react` to use.  It is already included as part of our `create-react-app` dependency, so I removed our explicit dev dependency.  Linting should start working again.
`yarn lint` continues to work.
> Remove explicit eslint-plugin-react dependency

- frontend/.eslintrc.json
- frontend/package.json
- frontend/src/pages/cans/detail/CanDetail.jsx
- frontend/src/pages/portfolios/list/PortfolioList.jsx
Our frontend linting was not actually linting anything.  It wasn't traversing the directory structure.  Now it does.
Now that ESLint traverses everything, I need to tell it to ignore CSS and SVG files since it doesn't know how to lint those files.
I also fixed some of the findings.
`yarn lint`
> Fix Frontend Linting

- backend/deployed_run.sh
- manifest.yml
We now load the test data every time we deploy to the dev environment.  Today, our dev environment's space name is `john.skinner`.  We'll update it when we get our own dev environment.
https://opre-ops-frontend-test.app.cloud.gov/portfolios
> Load Fake Data in Dev Environment

- .github/workflows/security_codeql.yml
- .secrets.baseline
- backend/opre_ops/django_config/settings/local.py
- cleanup from late reviews by @halprin ;) 
- tested, and looks like combining `language` on `codeql` saves ~30 seconds; mostly from standup/teardown of the job. I still like the separation; but will let it run-as is (combined) for now.
- cleaned up `local.py` - my goof
> issue-minor-cleanup

- backend/tests/ops_site/portfolios/test_portfolio_controller.py
Added another unit test to ensure that our `PorfolioSerializer` includes the list of CANs.
#376.
`pipenv run pytest`
> 376: Assert that the portfolio serializes a list of CANs

- .github/actions/deploy-backend/action.yml
- .github/actions/deploy-frontend/action.yml
- .github/actions/run-full-stack/action.yml
- .github/actions/setup-cloudfoundry/action.yml
- .github/actions/setup-javascript/action.yml
- .github/actions/setup-python/action.yml
- .github/workflows/ci.yml
- .github/workflows/dev_deploy.yml
- .github/workflows/nightly_scans.yml
- .github/workflows/unit_test_reusable.yml
- Major refactor of how the GitHub Actions are organized and run.
- Added a _nightly_ scan action; performs owasp-zap scans nightly
One driving factor for this was the repetition we had even across multiple `setup-node` or `setup-python`; if we ever changed versions of node or python, we'd have to update in multiple places. Further, I identified a few areas where we'd want to do the same thing multiple times like stand up the full-stack for e2e or DAST testing. So refactored many of the repetitive steps into their own local-actions. This is a first attempt at cleanup.
> tech-debt: Refactor GitHub Actions

- .pre-commit-config.yaml
Fixes our pre-commit rules so they actually run our frontend and backend linting on commit.
There were two issues.
- The frontend was using `types` which is _anded_.  This meant that it would only run if a file was `javascript`, `jsx`, `css`, _and_ `html`.  Generally no file is all of those.
- The `entry` is not executed in a shell by default.  Since we were using shell-isms (e.g. `&&`), we needed to be explicit with running our command in `bash`.
After making changes that violate our linting rules, do a `git add .` and then run `pre-commit run`.
> Fix Local Pre-commit Hooks

- frontend/src/components/PortfolioFundingSummary/PortfolioFundingSummary.jsx
The explanatory text about budget summary information to revise the subject verb agreement. The previous text came from a time when there were in fact multiple graphs planned.
#460 
Visit /portfolios/6 for instance and see that the text is altered.
> correcting subject verb agreement on portfolio details

- README.md
- frontend/src/components/PortfolioDescription/PortfolioDescription.jsx
- Added functionality for a user to click "show less" after having previously clicked "read more" or anywhere in the block of collapsed description text to see a full portfolio's description.  Clicking "show less" will collapse the description down to the original state. 
- Removed a now-outdated portion of repo README referencing Django 
#461 
Access a portfolio, click on "read more" and then click on "read less", ad infinitum
> 461: "show less" functionality on portfolio descriptions

- frontend/src/components/PortfolioDescription/PortfolioDescription.jsx
After further review, the "show less" text/span on a portfolio's description is supposed to be inline and immediately following the sentence of the last paragraph of a given description, but before any external link for the portfolio. As opposed to on a new line.  This PR corrects not only the text placement, but because it has to be only printed at the end of the last paragraph, the rendering of each paragraph is no longer equal and is treated conditionally instead. 
#461
> making show less to be inline on the last paragraph of a description

- frontend/cypress/e2e/portfolioDetail.cy.js
- frontend/src/components/PortfolioSummaryCards/PortfolioCarryForwardFunding.jsx
- frontend/src/components/PortfolioSummaryCards/PortfolioNewFunding.jsx
Updates to the wording on a couple of the Portfolio Summary cards on the Portfolio Details page to match updated designs and based on recent user feedback and PO requests earlier this week. 
#571 
It's currently deployed [in the dev environment](https://ops-dev.fr.cloud.gov/portfolios/6).
_
> 571: minor wording changes based on recent user feedback

- frontend/cypress/e2e/portfolioDetail.cy.js
- frontend/src/components/PortfolioSummaryCards/PortfolioNewFunding.jsx
Re-inserting the word funding instead of budget on the middle summary card of portfolio details after it got lost in some reconciliation of branches
#571
> funding not budget

- data-tools/data/user_data.json5
- frontend/cypress/e2e/portfolioDetail.cy.js
- frontend/src/components/Portfolios/PortfolioTeamLeaders/PortfolioTeamLeaders.jsx
- frontend/src/components/Portfolios/PortfolioTeamLeaders/styles.module.css
Fixing CSS & adding team leaders to every portfolio for 466.
[466 - Portfolio Team Leader(s)](https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/466)
Start up the app, check the portfolios int he front end. There should be team leaders for every portfolio, and the spacing should be fixed.
> 466 part deux

- frontend/src/components/UI/Tag/Tag.jsx
fixes hover color for a11y contrast issue
just noticed one small change needed for user story 597 (improve layout of CAN status and amounts). The font color on hover for the Funding Expected should be changed from white to black (#1B1B1B)
hover over `funding expected` in can card and see font color.
> fixes hover color for a11y contrast issue

- README.md
- backend/data_tools/data/can_data.json5
- backend/data_tools/data/research_project_data.json5
- backend/data_tools/data/user_data.json5
- backend/data_tools/src/import_static_data/import_data.py
- backend/ops_api/ops/resources/cans.py
- docker-compose.e2e.yml
- docker-compose.yml
- frontend/cypress/e2e/auth.cy.js
- frontend/cypress/e2e/canDetail.cy.js
- frontend/cypress/e2e/mainPage.cy.js
- frontend/cypress/e2e/portfolioDetail.cy.js
- frontend/cypress/e2e/portfolioList.cy.js
- frontend/cypress/support/e2e.js
- frontend/src/components/Auth/AuthSection.jsx
- frontend/src/components/Auth/ProtectedRoute/ProtectedRoute.jsx
- frontend/src/components/Auth/auth.js
- frontend/src/components/UI/Header/Menu.jsx
- frontend/src/components/UI/Header/User.jsx
- frontend/src/components/Users/UserInfo/UserInfo.jsx
- frontend/src/helpers/backend.js
- frontend/src/index.jsx
* Created Protected Routes, for non-authenticated endpoints
* Put some sample authorization control on the Menu - Now you only see /cans unless you're authenticated.
* Updated the way e2e performs the `fakeLogin` based on the new auth rules in the site.
* Updated docker-compose `data-tools`, since they shouldn't need to depend on `backend` anymore
#715 
1. Visit site unauthenticated, you should only see CANs in the menu.
1. Attempt to visit /portfolios, you should be redirected back to the homepage.
2. Login, you should now see Portfolios, CANs, and navigate as usual.
> OPS-715 Login Redirect

- .github/ISSUE_TEMPLATE/bugs.md
- .github/ISSUE_TEMPLATE/feature_work_template.md
- .github/ISSUE_TEMPLATE/generic-issue-template.md
* Adding or editing YAML frontmatter on GH issue templates
* Removing the overly prescriptive "so that" clause of the user story statement
N/A
* Create a new issue from one of the types
N/A
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
> editing yaml frontmatter on issue templates

- .github/workflows/nightly_scans.yml
The URL supplied for the dev environment used by the nightly OWASP Zap scan.
n/a
check produced serif file
n/a
n/a
> correcting url used for zap scan

- backend/models/cans.py
- backend/ops_api/ops/history.py
- backend/ops_api/ops/resources/cans.py
- backend/ops_api/ops/utils/query_helpers.py
- backend/ops_api/tests/ops/can/test_can.py
Add `search` query param to `/cans` endpoint.
https://github.com/HHS/OPRE-OPS/issues/742
1. Send GET request to backend: `http://localhost:8080/api/v1/cans?search=XXX8`
2. You should only get back 1 CAN in the response corresponding to `"number": "G99XXX8"`
> Ops 742 can search

- frontend/src/api/getAgreements.js
- frontend/src/pages/budgetLines/AgreementSelect.jsx
- frontend/src/pages/budgetLines/CreateBudgetLine.jsx
- frontend/src/pages/budgetLines/ProjectSelect.jsx
- Updated AgreementSelect to use only a uswds-select instead of combobox
- updated the `getAgreementsByResearchId` api call
- refactored the ProjectSelect and CreateBudgetLine components.
#818 
Unit Tests - TODO: update E2@
> wired up agreements

- frontend/src/pages/budgetLines/PreviewTable.jsx
- frontend/src/pages/budgetLines/TotalSummaryCard.jsx
Added summary blocks for Drafts, current fiscal year, and total agreements in the create new budget line/budget lines section.
[Create BLI Details - "Total Summary Cards" Components #809](https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/809)
Go to site, choose "Create Budget Line", follow prompts until you get to the budget lines section, and the three blocks appear under the table of budget lines on that page. Adding/removing/changing budget lines affects the totals appropriately.
> Ops 809 total summary cards

- backend/models/cans.py
- backend/ops_api/ops/resources/budget_line_items.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
Backend: Allow creating a BudgetLineItem with only an `agreement_id` (all other attributes are optional)
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/674
- POST to  `/budget-line-items` with a body of `{"agreement_id": 1}`
- You should get a 201 response back like:
```
{
"agreement_id": 1,
"amount": null,
"can_id": null,
"comments": null,
"created_by": 12,
"created_on": "2023-04-18T15:54:07.969886",
"date_needed": null,
"id": 20,
"line_description": null,
"psc_fee_amount": null,
"status": null,
"updated_on": "2023-04-18T15:54:07.969886"
}
```
> Ops 674 only agreement id required bli

- frontend/src/api/postBudgetLineItems.js
- frontend/src/pages/budgetLines/CreateBudgetLine.jsx
- frontend/src/pages/budgetLines/PreviewTable.jsx
- frontend/src/pages/budgetLines/createBudgetLineSlice.js
Add click handler/function to POST to `budget-line-items`. 
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/674
- Go to the Add New Budget Lines wizard and add a few BLIs to the Preview Table.
- Click Continue
- You should see the BLIs created in the logs in the back end.
> Ops 674 post bli from frontend

- backend/data_tools/data/agreements_and_blin_data.json5
- backend/models/cans.py
- backend/ops_api/tests/ops/can/test_product_service_code.py
The name and NAICS are essentially key/value pairs. There's an additional program support code string that relates back to and derived from the product service code. So I'm updating the model to accommodate and provide the sample values that OPRE has identified that we need.
#775 
Create an agreement and ideally these values will be present
> correcting model for product_service_codes

- backend/models/cans.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
- backend/ops_api/tests/ops/can/test_budget_line_item_status.py
- frontend/src/pages/agreements/list/AgreementTableRow.jsx
Added `UNDER_REVIEW` status to BLI.
https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/803
- Change a BLI in the DB to `UNDER_REVIEW`
- The Agreement associated with the BLI should show `In Review`
> Ops 803 under review bli status

- frontend/src/pages/agreements/StepCreateAgreement.jsx
- frontend/src/pages/agreements/StepSelectProject.jsx
There's a header at the top of the page when creating an agreement that's actually saying "Create Budget Lines" before they've actually started doing that. Specifically, it's on the step 1 (select project) and 2 (create agreement) pages. Additionally, some of the instruction text needed to be altered slightly to avoid placeholder text or reflect the latest designs.
#775 
This came up in a conversation with UX team on Monday.
Attempt to create a new agreement and check the header on step 1 and 2
From `development` where the branch is deployed:
https://docs.google.com/document/d/1Poj3OAnXZY3518gUNlbUoAyaoZjJkqUghcRTxOFKWTY/edit
> fixing header language when creating agreement

- backend/ops_api/ops/resources/health_check.py
- backend/ops_api/ops/utils/health_check.py
- backend/ops_api/tests/ops/health_check/test_health.py
The health check endpoint, /api/v1/health/, now performs simple checks for the database and the auth server.
This is a experimental feature, but I don't think the /health endpoint is being used yet.
The pool_status may not make sense since it's only for the node it's executed on and you might have more than one in prod.  However, I put a timeout on the test query, so when the pool is busy it shouldn't wait for ages to respond.  It such a case seeing the pool is all checked out when the db conn test failed would be meaningful.
Run the app and check http://127.0.0.1:8081/api/v1/health/
With both the database and OAuth server working the response would be
```json
{
"alarm_level": 0,
"checks": {
"auth_services": {
"alarm_level": 0,
"status_code": 200
},
"database_connection": {
"alarm_level": …
```
> add health checks for the database and OAuth server (to /api/v1/health/)

- frontend/src/helpers/utils.js
- frontend/src/helpers/utils.test.js
- frontend/src/pages/agreements/AgreementReasonSelect.jsx
- frontend/src/pages/agreements/AgreementTypeSelect.jsx
- frontend/src/pages/agreements/list/AgreementTableRow.jsx
Codes in ALL_CAPS (from ENUMs) were used as the display text of select boxes.  This changes those to use standardized friendly text using a method that can be used for any other situation where text needs to converted for display. 
[OPS-996](https://github.com/HHS/OPRE-OPS/issues/996)
View the Agreement Type and Agreement Reason select boxes in the create agreement form to see value like "CONTRACT" has been replace with "Contract".   And complete the create agreement process to verify that the valid codes are still being submitted.
> OPS-996 convert type codes to display text

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- backend/Dockerfile.debug
- backend/data_tools/environment/local.py
- docker-compose.debug.yml
- frontend/Dockerfile
- frontend/package.json
* Added `.vscode/launch.json` to allow VSCode to attach to running docker process and enable remote debugging.
* Added `.vscode/tasks.json` with a tasks that checks to see if the `ops-backend` container is running, if not, executes `docker compose up`
* Created `debug` versions of `docker-compose.yml` and `Dockerfile.debug` to facilitate opening ports, and installing `pydebug`
Within VSCode:
1. Go to a file you wish to debug ex: `backend/ops_api/ops/__init__.py`
2. Place a breakpoint on the line you'd like to pause on, ex: line 39: `log_level = "INFO"...`
3. Press `F5` to enter debugging (or RUN --> Start Debugging)
* This should switch to the debug view
* You should see a terminal open, checking to see if `ops-backend` container is running. If it is, then it should continue, and you …
> TeckDebt - Create vscode launch/tasks for debugging Python

- backend/models/cans.py
- backend/ops_api/ops/db.py
- backend/ops_api/ops/resources/agreements.py
- backend/ops_api/ops/utils/query_helpers.py
- backend/ops_api/tests/ops/agreement/test_agreement.py
* Added filtering (AND-type) on any combination of fields defined in the dataclasses for the different Agreement types.
* Restructured QueryHelper to allow for multiple WHERE clauses to be defined and then added to the query statement it returns.
* Updated tests to validate that it works. Improved query for GET /agreements to be able to dynamically choose the right class for a record from any of the Agreement model classes.
#1030 
1. `pytest`
2. Can also use the various parameters from a GET for `/agreements`. Like: GET `/agreements?contract_number=CT00XX1`
N/A
N/A
> Ops 1030 backend agreements filtering params

- .github/workflows/dev_deploy.yml
- .github/workflows/staging_deploy.yml
* Updated the `dev_deploy` to also trigger on the completion of CI workflow in `main`, resulting in the deployment to main, on any successful push to main, after CI completes. i.e.: All merged PRs will be deployed to DEV
> Added workflow pre-condition to deploy on main push

- backend/models/events.py
- backend/ops_api/ops/resources/agreements.py
- backend/ops_api/ops/utils/events.py
- backend/ops_api/tests/ops/agreement/test_agreement.py
It is now possible to delete contracts that only have BLIs in DRAFT status.
#1074
pytest does the test.
N/A
N/A
> Ops 1074 implement delete agreements

- frontend/cypress/e2e/notificationCenter.cy.js
- frontend/src/components/Auth/AuthSection.jsx
- frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx
Use different icon depending on if there are notifications.
https://github.com/HHS/OPRE-OPS/issues/1198
1. Log into the app and click the bell to see your notifications.
2. Clear the notifications.
3. The bell icon should change.
> Ops 1198 bell icon

- backend/data_tools/data/user_data.json5
- backend/ops_api/tests/ops/notification/test_notification.py
Adding a defined user entry for myself back into `user_data.json5` in the `data_tools container`. Another sign the authz is working! Huzzah!
N/A
I'll try to log in once again without the error messages (kudos for error messages!)
> re-adding myself back in as a user

- frontend/src/api/opsAPI.js
- frontend/src/pages/agreements/list/AgreementTableRow.jsx
- frontend/src/pages/agreements/list/AgreementTableRow.test.js
- frontend/src/pages/agreements/list/AgreementsList.jsx
- adds api call and wires up trash icon for deleting Agreements
- does not include:
-  Create a notification, which reflects the status of the deletion (success or fail)
- Enforce a subset of the rules on the frontend as well
- Optional - give Tooltip feedback on why DELETE is disabled (?)
#1294 
1. create an agreement or add yourself to an agreement that only has DRAFT budget lines.
2. In the Agreement list, click on the trash can icon
3. 💰 profit
> adds api call and wires up trash icon

- frontend/src/api/opsAPI.js
- frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
- frontend/src/pages/agreements/list/AgreementsList.jsx
- Adds error Alert for api calls that fail on agreement creation
Does not include: 
- add generic error page for api errors
- update validation for Agreement type select
- add/update e2e tests
#1318 
1. create an Agreement without selecting a Project Type
2. watch for error Alert
https://github.com/HHS/OPRE-OPS/assets/4629398/79adc1e3-b7c2-4df0-9c31-c0c89b789c66
> Ops 1316/task 1318

- frontend/src/pages/agreements/list/AgreementTableRow.jsx
Adds agreement name in Alert when successfully deleting agreement
#1036 
1. create agreement and remember Agreement Title
2. delete agreement
3. see Agreement title in the success Alert
https://github.com/HHS/OPRE-OPS/assets/4629398/66566f2b-21e6-422c-8451-13b8dc216f5c
> Adds agreement name in Alert when successfully deleting agreement

- frontend/src/pages/agreements/EditAgreement.js
- frontend/src/pages/agreements/details/AgreementBudgetLines.js
- frontend/src/pages/agreements/details/AgreementDetailHeader.js
- frontend/src/pages/agreements/details/AgreementDetails.js
- frontend/src/pages/agreements/review/ReviewAgreement.jsx
- checks BLIs to see if any are in IN_EXECUTING or OBLIGATED
- hides edit button if Agreement is not editable
- pertaining to editing an Agreement from Agreement detail page
Does not cover
- wizard workflows 
- e2e tests
#1362 
1. Goto Agreement list and select first agreement // BLIs in DRAFT
2. should let you edit it
3. Goto Agreement list and select second agreement // BLIs in Obligated and Executing
4. should NOT let you edit it
https://github.com/HHS/OPRE-OPS/assets/4629398/6c9b0631-ccce-49cf-badb-aa4b16defc40
> adds checks to disable editing

- backend/ops_api/ops/environment/cloud/dev.py
- backend/ops_api/ops/environment/cloud/staging.py
* Incorrect `redirect_uri` in the dev and staging configs for cloud environment
Login with Login.gov via the dev or staging cloud environments (after release)
> Config patch 112

- frontend/jsconfig.json
Getting red squiggles on React modules, but this setting was overriding the template in the jsonfig:
> fixes React linting issue

- backend/models/cans.py
- backend/ops_api/ops/resources/budget_line_item_schemas.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
- openapi.yml
Add `team_members` property to BLI.
https://github.com/HHS/OPRE-OPS/issues/1394
HTTP GET `/budget-line-items` and you should get back a `team_members` array in each BLI object.
> Ops 1394 add team members to bli

- backend/data_tools/src/import_static_data/load_db.py
- backend/models/base.py
- backend/models/history.py
- backend/models/users.py
- backend/ops_api/ops/resources/agreements.py
- backend/ops_api/ops/resources/budget_line_items.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
This fixes the bug found that when an Agreement's BLIs were edited and then saved, ALL of the BLIs, whether they were edited or not, that were in `PLANNED` would be set to `DRAFT` status.
The corrective was to validate if a BLI actually was changed or not. If not, then the status will not be changed.
#1379 
Start up OPS locally
Log in as an admin
Navigate to Agreements
Edit "DIRECT ALLOCATION #2: African American Child and Family Research Center"
Go to Budget Lines tab
Choose to edit the BLIs.
Select 1 of the BLIs in `PLANNED`, change something, save the BLI.
Go to bottom of page, save all changes.
Notice that only that 1 `PLANNED` BLI is now set to `DRAFT`, while all other `PLANNED` BLIs remain in their current status.
N/A
> Ops 1379 bug squashing

- frontend/cypress/e2e/agreementDetailsEdit.cy.js
- frontend/src/components/UI/WizardSteps/StepCreateBudgetLines/StepCreateBudgetLines.jsx
- frontend/src/pages/agreements/details/Agreement.js
- frontend/src/pages/agreements/details/AgreementBudgetLines.js
Moves Alert to Agreement Details parent
- originally on the Agreement BLI tab
- will need to figure out to show BLI group updates
#1432 
1. Edit an Agreement from the Agreement Detail page
2. See Success alert
> Moves Alert to Agreement Details parent

- backend/ops_api/ops/history.py
- backend/ops_api/ops/resources/agreement_history.py
- frontend/cypress/e2e/agreementDetailsEdit.cy.js
- frontend/src/api/getAgreementHistory.js
- frontend/src/api/opsAPI.js
- frontend/src/components/Agreements/AgreementDetails/AgreementHistoryList.js
- frontend/src/components/Agreements/AgreementDetails/AgreementHistoryPanel.jsx
- frontend/src/components/Agreements/AgreementDetails/InfiniteScroll.js
- frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
- frontend/src/helpers/utils.js
- frontend/src/pages/agreements/details/AgreementDetails.test.js
- frontend/src/pages/agreements/details/AgreementDetailsView.js
Implemented infinite scrolling for the Agreement History panel.
This gets pages of 20 records as one scrolls to the bottom of the history panel.
This implementation uses Axios instead of RTK due to issues with this approach to infinite scrolling and RTK.
#1385 #1300 
Edit an agreement and/or it's BLIs (multiple times) and view the history on the details page.  Scroll in the history panel to load more history records.  You can edit the pageSize in frontend/src/api/getAgreementHistory.js if you want to test with smaller pages and more loads.
> Agreement History - Infinite Scrolling

- frontend/cypress/e2e/editAgreementAsBasicUser.cy.js
- frontend/src/constants.js
- frontend/src/pages/agreements/EditAgreement.js
- frontend/src/pages/agreements/details/AgreementDetails.js
- frontend/src/pages/agreements/list/AgreementTableRow.jsx
- frontend/src/pages/agreements/review/ReviewAgreement.jsx
fixes bug allowing basic user to attempt to modify agreements
#1416
1. Login as basic user
1. Goto agreements list
1. Try to select edit icon // should NOT allow
1. Go to Agreements detail // no edit icon
1. Go to review an agreement // edit button is disabled
1. Hack url `/agreement/edit/{id}` // error Alert shown
- ~~OESA: Dependency rules followed~~
> fix: :bug: fixes basic user editing agreements

- frontend/cypress/e2e/agreementDetails.cy.js
- frontend/cypress/e2e/agreementDetailsEdit.cy.js
- frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
- frontend/src/components/UI/Form/CreateBudgetLinesForm/CreateBudgetLinesForm.jsx
- frontend/src/components/UI/Form/TextArea/TextArea.jsx
- frontend/src/pages/agreements/details/AgreementDetailsView.js
* adds display of the Agreement notes field on the details page
* implements character limits on the text area input used for Agreement.notes
* this same input is used for Agreement.description and CLI.comments (notes), so I added the character limits of 1000 and 150 for those
#1301 
* edit an agreements description and view the details page
> OPS-1301 View an agreement's note

- frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
fix for the the project officer combo box being empty when edit an agreement with a project 
NOTE: this removes code which says that it's a workaround for a caching problem, but I can't replicate that now
#1537 
* edit an agreement which already has a project officer, the project officer combobox should be populated with that
- ~[ ] OESA: Code refactored for clarity~
- ~[ ] Form validations updated~
> fix: current project officer not being selected in edit form

- .github/workflows/security_semgrep.yml
Using a pinned version (based on sha) of the `semgrep` container rather than relying on `latest`. Among other benefits, it helps us avoid bugs they inadvertently introduce...
https://github.com/returntocorp/semgrep/issues/9091
See if CI passes 😉 
https://hub.docker.com/layers/returntocorp/semgrep/1.47.0/images/sha256-e7216f0ec1eaa032f470733e33d4a49d556f04b82fdce5e066599c38c1334c32
> Using a pinned version of the newly-upgraded semgrep container

- .pre-commit-config.yaml
Simple change, for those who newly install pre-commit, or run with `--all-files`, this will NOT modify the USWDS .svg files by adding a newline.
1. run `pre-commit run --all-files` from the root of the project
2. You should NOT see any .svg files within `frontend/src/uswds` modified
> Exclude USWDS .svg files from eol pre-commit

- terraform/eus/dev/frontend_asa/context.tf
TF linting removed a data source that is needed for output... caused failure in the action. Added back the source block.
> chore: Added front-end deploy fix

- .github/renovate.json
PR #1754 was attempting to update several packages to newer versions. The particular issue going on with the CI workflows on that PR was that the runner could never fully get the full installer for cypress completely downloaded and fails to get completely downloaded. On occasion when re-attempting, it complains about other similar symptomatic issues related to performance and timeouts. After some research and debugging, bun versions > 1.0.16 seem to have a performance change on `install` that is causing this. Until this is worked out, I'm proposing we pump the brakes on `bun` upgrades. 
I've set myself a reminder to re-assess this periodically
see if renovate stops attempting to upgrade bun
> Ceasing bun upgrades for now

- backend/ops_api/ops/resources/workflow_approve.py
- backend/ops_api/tests/ops/workflows/test_workflow_approve.py
- frontend/cypress/e2e/agreementWorkflow.cy.js
- frontend/src/pages/agreements/approve/ApproveAgreement.js
* Implements REJECT for a workflow step in the back end (/workflow-submit)
* Implements Decline button action in the front end to perform the reject
#1525 
On the Approve Agreement page, click the Decline button.
Also run the e2e tests, which has a new test in `agreementWorkflow.cy.js` to test the reject function
> OPS-1525: Adds REJECT of workflow step

- terraform/eus/dev/backend_asa/context.tf
- terraform/eus/dev/frontend_asa/context.tf
Changed the source to relative path until we can figure out a better solution. 
Renovate changed the tags for the context module to something pre-terraform.
> chore: Just changed the source to relative path for now.

- frontend/Dockerfile.azure
Should work without, but tested to require some NODE_ENV
Added NODE_ENV to the entrypoint where the runtime env is set. 
Runtime env injection stopped working. Documentation indicates the NODE_ENV is not required for this to work, but testing proves it must be set to something... anything but development.
> fix: Add NODE_ENV

- backend/data_tools/src/import_static_data/import_data.py
- backend/models/cans.py
- backend/models/portfolios.py
* removes hard coded starting value of ID sequences of Identity columns (division and services_component)
* resets the sequences to max(id)+1 after data was loaded that manually set the ID (of any table that had an ID set in `import_data`) 
* this currently includes division, services_component, portfolio_url, funding_partner, funding_source, procurement_shop, product_service_code, clin
#1935 
run the tests - creating service components would fail on save to the DB if the sequence was left at 1
Also to check the value of sequences without incrementing them you use SQL like this
`SELECT pg_sequence_last_value('ops.division_id_seq');`
> OPS-1935 Reset identity sequences after data load

- backend/ops_api/ops/resources/budget_line_items.py
- backend/ops_api/ops/resources/services_component.py
- backend/ops_api/ops/utils/api_helpers.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
- backend/ops_api/tests/ops/can/test_services_component.py
The functions used by extra_check of `/budget-line-items` and `/services-components` were using the agreement_id coming in the request of a PUT/PATCH to allow authorization based on that agreement.  This change
* stops use of related agreement ID from the request to allow authorization for changes to BLIs or SCs
* stops allowing changes to related agreement ID in BLIs or SCs (via API)
#1938 
run tests
> OPS-1938 safer authorization for BLIs and SC

- frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
- frontend/src/components/UI/Button/GoBackButton/GoBackButton.jsx
- frontend/src/components/UI/Button/GoBackButton/index.js
- frontend/src/components/UI/Form/CreateBudgetLinesForm/CreateBudgetLinesForm.jsx
- frontend/src/components/UI/Modals/ConfirmationModal.jsx
- frontend/src/components/UI/WizardSteps/StepCreateBLIsAndSCs/StepCreateBLIsAndSCs.jsx
- frontend/src/components/UI/WizardSteps/StepCreateBLIsAndSCs/useCreateBLIsAndSCs.hooks.js
- frontend/src/pages/agreements/StepCreateAgreement.jsx
Adds GoBackButton and Cancel button to Step 3
- Refactor ConfirmationModal and AgreementEditForm components
#1967 #2019 
1. Goto Agreement Creation wizard
2. Goto Step 3 
3. Click on GoBack button
4. Will take you to Step 2
5. Go to Step 3
6. Click Cancel button
7. Will take you to Agreements list and remove the Agreement
> feat: :sparkles: Adds GoBackButton and Cancel button to Step 3

- .github/ISSUE_TEMPLATE/feature_work_template.md
In our February retro, we discussed and added an action item for making a new Definition of Done item for us to acknowledge that we have documented any design or technical debt that we couldn't go ahead and tackle in the same story/GH issue.  This change adds that new item to our feature/story GH issue template. 
N/A
N/A
https://flexion.teamretro.com/teams/6qdYqREFtyhJ6zCs5LkGb3?actionId=040480e9-43a7-4734-a18f-9b0acc83d4cc
> adding DoD item for new debt documentation

- backend/ops_api/ops/schemas/budget_line_item.py
- backend/ops_api/tests/ops/features/test_validate_draft_budget_lines.py
- backend/ops_api/tests/ops/features/test_validate_draft_budget_lines_in_workflow.py
- backend/ops_api/tests/ops/features/validate_draft_budget_lines.feature
- frontend/src/components/UI/WizardSteps/StepCreateBLIsAndSCs/useCreateBLIsAndSCs.hooks.js
* removed requirement for line_description
* removed the workaround of line_description="." 
More work related to this will come with #2020
This just removes the requirement for line_description
#1852 #2047 
run the tests
Or manually create budget lines in UI and verify that they have a null line_description.  This will also make display_name like BudgetLineItem#123 when line_description is null.  Which is displayed in the Agreement history.
> OPS-1852/task-2047 Remove requirement for line_description

- backend/ops_api/ops/resources/budget_line_items.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
This fixes an error that occurred with Patch (update) of a BLI with a null date
#2053 
run the test
`ops_api.tests.ops.can.test_budget_line_item.test_patch_budget_line_items_with_null_date_needed`
> OPS-2053: Fix error on patch BLI with null data_needed

- backend/ops_api/ops/utils/auth_views.py
During today's EoH, it was discovered that when the backend creates an access token, it's not setting the token's expiration correctly it seems. 
N/A
* Wait for token to expire (30 minutes) and see if token is still registered ?
> Update access token expiration

- frontend/Dockerfile.azure
Removed the global install for runtime-env-cra and move to local, updated the entrypoint. 
Base image seems to have broken bun installing globally
> fix: Changed from global install to local, fix permissions

- frontend/Dockerfile.azure
Added express to runtime install dependencies for azure. 
Server was failing to start in container.
> fix: need runtime dependency of express

- .github/renovate.json
Basically reverses #1872 and allows bun to be managed and kept upgraded with any other dependency. 
It's been about a month now since we've been on 1.1.8 and as long as bun has no regressions or other changes in behavior to prevent nominal co-existence with cypress and keep out node, then we should be all set to let it autoupdate
Watch CI/CD pipeline and let renovate do its thing each day.
N/A
> remove bun from exceptions on renovate upgrades

- backend/openapi.yml
just added a bit of missing openapi docs
> Add a couple of missing uses of requestor_notes, reviewer_notes in openapi docs

- .pre-commit-config.yaml
- It occurred to me that renovate is (sadly) not updating versions specified in the pre-commit config file so I'm doing some manual updating. Version `4.5.0` of the main hooks has some fixes necessary for some scenarios of f-strings in python 3.12, or [so they say](https://github.com/pre-commit/pre-commit-hooks/issues/971). 
- Also I'm removing the terraform config from our pre-commit since we don't have any files currently that it would scan anyway and since all our TF is in a different repo currently anyway.
none
test out your pre-commit locally on this branch if desired. 
N/A
> removing tf pre-commit and updating main hooks version

- frontend/src/components/Auth/MultiAuthSection.jsx
Given [John's recent PR](https://github.com/HHS/OPRE-OPS/pull/2494) that ripped out the config for login.gov in azure and given that our `redirect_uri `on the login.gov side only works for `localhost` anyway and not any hosted environment, I modified the conditional to only show the login.gov authn option when doing local dev. The intent is to create a better UX so that an unknowing user doesn't try to innocently auth with their login.gov sandbox account.
However, this presumes that we don't set the environment variable to something for the non-static FE container build or for local, which seems to be the current practice for the time being. 
N/A
Hit the front login page.  For any azure non-prod environment, you should see only AMS or AMS plus FakeAuth.  On localhost you should see all 3.
> hiding login.gov authn option for anything but local dev

- backend/data_tools/data/user_data.json5
Brings the `user` role the desired permissions for standard OPS users for our sample data load--matching the `user` role that's loaded for the `data-initial` load of a more-empty DB environment.
The context and impetus for this is that in #2541, the `COR` role was rightfully removed. However, necessary permissions were never added to the standard user role and thusly, presently, a standard `user` cannot do various PUTS and PATCHES that are necessary on certain objects
#2560 
* As User Demo, try creating a SC within a contract, a BL, and the contract itself. You should receive no errors. 
~- [] 90%+ Code coverage achieved~
> 2560: making sample data reflect `user` role matching that of `data-initial`

- frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.jsx
- frontend/src/pages/agreements/list/AgreementsFilterButton.jsx
removes validation from Agreement list filter for procurement shop.
#2706 
1. Goto Agreements list
2. open filter, no validation is set
3. create a new Agreement
4. select a different proc_shop than GCS
5. will show validation error
> fix: adds default to GCS

- .github/workflows/nightly_scans.yml
Updating the URL for the OWASP ZAP DAST scans to reflect the new staging environment URL and to actually download the ZAP action from the correct source. It had been trying to download from Docker Hub.
N/A
I tested locally but check result of nightly scans once merged
> updating OWASP ZAP DAST scans to use our new staging environment URL

- backend/ops_api/ops/auth/decorators.py
- backend/ops_api/ops/auth/service.py
- backend/ops_api/tests/auth/test_check_user_session.py
- backend/ops_api/tests/auth/test_login.py
- Remove check for IP address used in user session.
- Always create a new session at `/login`
While testing OPS in Azure we found that the client IP address was unpredictable and unreliable for this purpose. 
> remove ip check and always create a new session on login

- frontend/nginx.conf
Redirects the output for nginx's access and error logs from a file running in the container to the container's stdout. 
#2647 
ACF Tech has a requirement to see frontend web server logs, both access and error logs. Presently, the statically-built content for the frontend container deployed in Azure has Nginx's logging output going to a file and the LAW in Azure can't grab it from there and it needs to be in the ACA container's stdout for the KQL query in LAW to be effective.
Upon a redeploy in Azure, see if logging output ceases to the /var/log/nginx/* files and is going to the stdout viewable in Azure and in KQL queries.
N/A
> 2647: Changing nginx logs to stdout

- frontend/cypress/e2e/createAgreement.cy.js
- frontend/cypress/e2e/createAgreementWithValidations.cy.js
- frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
- frontend/src/components/Agreements/AgreementEditor/AgreementEditFormSuite.js
- frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
- frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/suite.js
- frontend/src/components/ServicesComponents/ContractTypeSelect/ContractTypeSelect.jsx
- frontend/src/components/ServicesComponents/ServiceReqTypeSelect/ServiceReqTypeSelect.jsx
- frontend/src/pages/agreements/approve/ApproveAgreement.jsx
- frontend/src/pages/agreements/review/suite.js
- adds missing Vest validation
#2770 
1. create min agreement
2. try to send to review
3. see validation errors
4. go to edit to fix errors
5. they should match
6. 💰 profit
> fix: 🛠️ adds missing validation on Agreement form

- backend/openapi.yml
- frontend/src/components/CANs/CANTable/CANTable.helpers.js
- frontend/src/components/CANs/CANTable/CANTable.helpers.test.js
- frontend/src/components/CANs/CANTable/CANTable.jsx
- frontend/src/components/CANs/CANTable/CANTable.test.jsx
- frontend/src/components/CANs/CANTable/CANTableHead.jsx
- frontend/src/components/CANs/CANTable/CANTableRow.jsx
- frontend/src/components/CANs/CANTypes.d.ts
#346 
1. Go to list of cans
2. see obligate_by as MM/DD/YY
> refactor: displays CAN obligate_by as MM/DD/YY

- frontend/cypress/e2e/canList.cy.js
- frontend/src/components/UI/FilterTags/FilterTags.jsx
- frontend/src/constants.js
- frontend/src/pages/cans/list/CANFilterButton/CANFiilterButton.jsx
- frontend/src/pages/cans/list/CanList.helpers.js
- frontend/src/pages/cans/list/CanList.helpers.test.js
fixes UX review items
#347 
https://github.com/user-attachments/assets/e5ab7a92-7e4a-4a5e-861f-6b75061748ae
> style: 💅 UX Review fixes

- frontend/src/pages/cans/list/CANFilterButton/CANFilterButton.hooks.js
One way to potentially solve not showing the budget pills when there is no user interaction with the budget range slider. 
https://github.com/user-attachments/assets/35668d70-5c98-4893-af6c-361d0e661cfc
> fix: remove budget pills with state using defaults

- backend/openapi.yml
This PR updates the openapi.yml file to reflect changes to the  CAN Funding Summary (`/api/v1/can-funding-summary/{can_id}`)  endpoint for supporting [CAN Summary Information](https://github.com/HHS/OPRE-OPS/issues/2842) cards.
- Removed `can_id` path parameter
- Added `can_ids` query parameter: _Required_  list of CAN Ids
- Added `active_period` query parameter: Optional list of active periods
- Added `transfer` query parameter: Optional list of method of transfer types
- Added `portfolio` query parameter: Optional list of portfolios
- Added `fy_budget` query parameter: Optional list of exactly two values (min and max)
- Added `new_funding` to the response object: String value of the spending amount
[#2961](https://github.com/HHS/OPRE-OPS/issues/2961)
The openapi.yml file has been …
> fix: update can funding summary openapi spec

- backend/data_tools/data/user_data.json5
Adding in a couple of real human users with AMS accounts for non-prod environments
N/A
Verify if the named users can log in
> chore: adding requested user stakeholders for non-prod environments

- .github/workflows/release.yml
Bun does not seem to work well with `semantic-release` - attempt to use Node instead
> build: attempt to use node for dependency rather than bun

- backend/openapi.yml
`/api/v1/can-funding-budgets/` POST request body is [expecting a `budget` field](https://github.com/HHS/OPRE-OPS/blob/b13b4a435d21a460d2b0309e23d543d26c8d9644/backend/ops_api/ops/schemas/cans.py#L97). Change updates the `CreateUpdateCANFundingBudgetRequest` example in the openapi file to include `budget` and remove `funding`.
[3104](https://github.com/HHS/OPRE-OPS/issues/3104)
OpenAPI spec displays correct fields. 
N/A
<del>- [ ] 90%+ Code coverage achieved
<del>- [ ] Form validations updated
N/A
> docs: fix CreateUpdateCANFundingBudgetRequest example values

- backend/ops_api/ops/utils/cans.py
- backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
- frontend/src/components/CANs/CANSummaryCards/CANSummaryCards.jsx
- frontend/src/pages/cans/list/CANFilterButton/CANFilterTypes.d.ts
- frontend/src/pages/cans/list/CanList.helpers.js
- frontend/src/pages/cans/list/CanList.jsx
mob work from the week of 11/22/24
> feat: api integration is updating CAN List cards

- backend/openapi.yml
- backend/ops_api/ops/schemas/budget_line_items.py
- backend/ops_api/tests/ops/can/test_can.py
- frontend/src/components/Agreements/AgreementTypes.d.ts
- frontend/src/components/BudgetLineItems/BudgetLineTypes.d.ts
Include the following fields in the **_BudgetLineItem_** response object returned by the /cans/ endpoint:
- `agreement_name`
- `agreement_type`
- `awarding_entity_id` (Agreement Procurement Shop Code) 
[#3052 ](https://github.com/HHS/OPRE-OPS/issues/3052)
Unit tests passing. 
N/A
N/A
> 3052: Add additional agreement attributes to /cans/ response #3092

- backend/data_tools/tests/load_cans/test_load_cans.py
- backend/models/cans.py
- backend/openapi.yml
- backend/ops_api/ops/schemas/budget_line_items.py
- backend/ops_api/ops/schemas/cans.py
- backend/ops_api/tests/ops/can/test_can_funding_details.py
Use the fund code to determine the Funding Method, Funding Received, and Funding Type, and then add these values as properties to the CANS model.
[#3110 ](https://github.com/HHS/OPRE-OPS/issues/3110)
Ensure backend unit tests pass.
N/A
[Fund Code Mapping](https://lucid.app/lucidspark/601d8f63-4ee4-4c0b-b020-55581ea0cb7a/edit?viewport_loc=-218%2C-142%2C2658%2C1320%2C0_0&invitationId=inv_8c620359-ca47-4da4-85a9-0b754d0563a5)
> 3110: Add Funding Method, Received, and Type to CANS 

- backend/ops_api/ops/document/azure_document_repository.py
- backend/ops_api/ops/document/document_gateway.py
- frontend/cypress/e2e/uploadDocument.cy.js
Instead of having the azure document repository return a URI that is directly referencing the azure storage blob, instead change the URI to be the app gateway instead. Additionally, adjusted the SAS token generated to be limited to just the specified container (docs in the storage account) as opposed to the full account. 
[OPS-2362](https://github.com/HHS/OPRE-OPS/issues/2362)
Run unit tests
> OPS-2362: Refactor azure document repository to route through app gateway

- backend/ops_api/ops/urls.py
- frontend/cypress/e2e/uploadDocument.cy.js
The flask document routing for the GET /documents/<id> endpoint had a trailing slash, which is inconsistent with any of our other /route/<id> routes. This caused an HTTP308 (Permanent Redirect) When attempting to get the document list in our upload-document page. 
OPS-2362
Run all tests
> OPS-2362: Fix GET documents routing in flask 

- frontend/cypress/e2e/mainPage.cy.js
- frontend/src/pages/Home.jsx
Adds some conditional text for the center div when a user first logs in that's more appropriate for where we're at. This makes the experience for the staging environment match what we're about to enter into for Phase 0 as well as the production environment.  Eagerly inviting better suggestions for text/appearance/user experience. 
I don't love the repetition of that react component tag but eslint wasn't having it any other way....
N/A
Log in!
N/A
> fix: updating home landing page text based on environment

- frontend/cypress/e2e/canDetail.cy.js
- frontend/src/components/CANs/CANDetailForm/CANDetailForm.jsx
- frontend/src/components/CANs/CANDetailForm/CANDetailForm.test.jsx
- frontend/src/components/CANs/CANDetailForm/suite.js
- frontend/src/components/CANs/CANDetailView/CANDetailView.test.jsx
- frontend/src/pages/cans/detail/Can.hooks.js
- refactor agreement types count logic
- add component tests for new components
#310 #3098
> refactor: fix logic for agreement types count, add component tests

- backend/openapi.yml
Added `GET` `/can-history` to spec.
https://github.com/HHS/OPRE-OPS/issues/3215
> docs: update spec for /can-history

- .github/workflows/dev_be_build_and_deploy.yml
- .github/workflows/dev_fe_build_and_deploy.yml
- .github/workflows/prod_fe_build_and_deploy.yml
- .github/workflows/stg_fe_build_and_deploy.yml
changes the `imageToDeploy` for the staging frontend container such that it looks for a tag matching the environment (`stg`) instead of the sha of the image.
Although there are multiple possible ways to solve this, and maybe larger more wide-reaching solutions are warranted as part of #2758 or other initiatives, this seems a minimally-invasive change to make to fix the pain being experienced. maybe ? Better ideas welcomed. Never compromise on quality. 
This is being proposed/done because:
* Currently there's no difference at build time between the dev and staging frontend containers so they end up coming out with the same checksum/sha.
* the build GHA tries publishing image with tags matching the environment and the sha image. 
* The dev container image is usually taking a second or more …
> fix: updating the tag for the imageToDeploy for the frontend containers

- .github/workflows/nightly_scans.yml
Further modified the command line options to the ZAP docker container to further attempt to silence warning-level and below threshold of findings. This is believed to be the intent of the current config but it has been still producing an undesirable level/quality of findings.
This is a pre-cursor to a future PR that will change this action over to testing the production environment instead of the staging environment.
N/A
Manually run or wait for scheduled run of this GHA and see if warning-level issues and below are produced.
https://www.zaproxy.org/docs/docker/full-scan/
https://github.com/marketplace/actions/zap-full-scan
> chore: update ZAP DAST scan to ignore warning and below

- .github/workflows/dev_be_build_and_deploy.yml
- .github/workflows/prod_be_build_and_deploy.yml
- .github/workflows/stg_be_build_and_deploy.yml
The terraform for the backend containers when they're initially getting created or re-created really want a good image tag to use for deploying and since we weren't doing any tagging other than the sha and recently got rid of the unstable tag for dev, this is an off-nominal situation. So until our semantic versioning/release stuff gets more implemented, this is a near-term hack of sorts to allow the ACAs to be more happy when getting created as we've had to do this week and in the event we need to do it again.   
Regular typical deploys though will still specify images via sha as they have been doing.
Blow away the backend ACAs and re-create
> chore: adding environment label to backend container builds as well

- frontend/cypress/e2e/canDetail.cy.js
- frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.jsx
- frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
- frontend/src/components/CANs/CANFundingReceivedForm/CanFundingReceivedForm.jsx
- frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTable.jsx
- frontend/src/components/UI/DataViz/LineBar/LineBar.jsx
- frontend/src/pages/cans/detail/Can.hooks.js
- frontend/src/pages/cans/detail/Can.jsx
- frontend/src/pages/cans/detail/CanFunding.hooks.js
- frontend/src/pages/cans/detail/CanFunding.jsx
- adds welcome modal to can funding received tab
#310 #3299 
1. e2e tests pass or:
2. goto `cans/504/funding`
3. click on edit
4. see welcome modal
5. 💰profit
6. add funding and save
7. click on edit
8. welcome modal should not appear
- <del>[ ] Form validations updated
> feat: adds welcome modal to can funding received tab

- frontend/cypress/e2e/portfolioDetail.cy.js
- frontend/cypress/e2e/portfolioList.cy.js
- frontend/src/components/UI/Header/Menu.jsx
- frontend/src/index.jsx
Removes the Portfolios menu option from the horizontal navigation in OPS based on discussions this week
N/A
Log in and see if the Portfolios menu option is displayed
> Hide portfolios UI menu option temporarily

- .github/workflows/nightly_scans.yml
- .github/workflows/security_codeql.yml
- .github/workflows/security_semgrep.yml
Reverting codeql version back to a known-working version (3.28.6) as 3.28.8 seems to have broken things that use it.
codeql was recently upgraded in #3378 but the various security GHA have been failing since then. 
Wait for the next CI run  and nightly run
https://github.com/github/codeql-action/blob/v3.28.8/CHANGELOG.md
>  reverting codeql version

- backend/ops_api/ops/schemas/cans.py
- backend/ops_api/tests/ops/can/test_can_funding_received.py
The mapping for the funding received amount is incorrect. It should be a float (or decimal) instead of an integer.
[See @fpigeonjr's comment on #3465](https://github.com/HHS/OPRE-OPS/issues/3465#issuecomment-2657920963)
Create a `funding received` from the frontend and check that the backend returns the `funding` value as a decimal.
https://github.com/user-attachments/assets/851ed001-aa65-4936-b060-2c5e3c7b9b4c
N/A
> fix: correct type on funding received response

- frontend/cypress/e2e/helpCenter.cy.js
- frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
- frontend/src/pages/help/Feedback.jsx
- frontend/src/pages/help/Feedback.test.jsx
- frontend/src/pages/help/HelpCenter.jsx
- frontend/src/pages/help/HowToGuides.jsx
- frontend/src/pages/help/HowToGuides.test.jsx
* Changed the text in the Help Center to say "How-to guides" instead of "User guides"
* Removed the "plus" from the button when updating a CAN's FY budget, but keep it for adding when not previously existing
* Removes the table of contents from the How-to Guides tab of the Help Center
#3490 
Log in to the UI, access the UI elements in question
> Phase 1 launch day UI tweaks

- frontend/cypress/e2e/canList.cy.js
- frontend/src/components/CANs/CanTabs/CanTabs.jsx
Hiding the clickable My CANs tab until such time as that feature is fully developed
#3522
Verify that the My CANs tab is removed
> Hide "My CANs" tab

- frontend/cypress/e2e/portfolioDetail.cy.js
- frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Filtering portfolio funding can by budget year instead of can fiscal year.
#3274 
1. e2e test pass or test manually
1. goto portfolio 1, portfolio funding tab.
1. select fiscal year 2023 
1. should show 2 can cards
1. switch to fiscal year 2021
1. should show 2 can cards
> Hotfix: fixed can id filtering

- frontend/src/pages/help/Glossary.jsx
Removed Planned Mod from the list of BL statuses in the Glossary. Planned Mod Status is an out-of-date design that we did not end up using. Thus, its not going to appear as a status and does not need to be included in the glossary
Removed Planned Mod from the list of BL statuses in the Glossary
edited the definition for Budget Line Status
Click on Glossary
Navigate to Budget Line Status
Review listed BL statuses
> Remove Planned mod from Glossary.jsx

- frontend/cypress/e2e/canList.cy.js
- frontend/src/components/CANs/CANTable/CANTable.jsx
- fixes #3540 pagination bug
- navigate to CANs list, select FY23
- apply filter for “1 year” active period and see results
- clear filter
- start again at CANs list, FY23
- click page 2
- apply filter for “1 year” active period and see 0 results :bug:
- 💰 but now you will see results
> fix: add pagination fix for CAN list filtering

- frontend/src/components/UI/Header/Menu.jsx
- frontend/src/pages/help/HelpCenter.jsx
Auto-select the How-to Guides when on the Help Center page.
Point 2 of @npage123's review on [#3320](https://github.com/HHS/OPRE-OPS/issues/3320)
- Test passes.
- Navigating to `/help-center` or `/help-center/`, or clicking the **Help Center** button in the main navigation, will take you to the Help Center page with the _How-to Guides_ section automatically selected.
https://github.com/user-attachments/assets/17550b27-7059-4da0-a403-10c87a943596
None
> feat: auto select how-to guides in help center

- frontend/cypress/e2e/reviewAgreement.cy.js
- frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
- update button text for budget line status change
- closes #3402 
1. goto agreements/budget lines tab
2. see button label
3. 💰 profit
> style: update button text for budget line status change

- backend/data_tools/src/load_budget_lines/utils.py
- backend/data_tools/src/load_data.py
Create a starting script for loading BLIs and add a new type option to the main shell script. 
The primary goal of this change is to create a starting script that can be used for testing the container app job and ensuring that uploading a spreadsheet triggers the `transform` function. 
[#3590](https://github.com/HHS/OPRE-OPS/issues/3590)
Spin up the stack and ensure that running the command `python data_tools/src/load_data.py --env dev --type budget_lines --input-csv data_tools/test_csv/contract_budget_lines.tsv` from the `backend` generates the log "transform triggered":
```
2025-03-25 05:49:56 | INFO     | __main__:main:71 | Starting the ETL process.
2025-03-25 05:49:56 | INFO     | __main__:main:71 | Starting the ETL process.
2025-03-25 05:49:57 | INFO     | __main__:main:82 | …
```
> feat: add starting script for loading blis to test container app job

- .github/ISSUE_TEMPLATE/bugs.md
Abandons the legacy `bug` label used as a default label on new bug issues and instead defaults to `bug-medium` leaving the user to change the label as desired
N/A
Create a new GH issue of type bug
> Update bug template with new label

- frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
- frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.test.jsx
make api call to agreements/{id} to get the procurement shop data
Procurement shop was missing
#3648
1. goto Budget Lines list
2. open table row
3. see procurement shop
> fix: proc shop to AllBLIRow

- frontend/cypress/e2e/agreementDetails.cy.js
- frontend/cypress/e2e/editAgreement.cy.js
- frontend/cypress/e2e/researchProjectDetail.cy.js
- frontend/src/pages/agreements/details/Agreement.jsx
- frontend/src/pages/agreements/details/AgreementDetailsView.jsx
- frontend/src/pages/portfolios/list/PortfolioList.jsx
- For agreeements that are grants, IAAs, AAs and direct obligation; hide the description and hide the notes (I believe this came up in team collab, that these agreements don’t have descriptions so no need to display that)
- For some reason, when I view a direct obligation, I am seeing both banners (the banner for other agreement types and the banner for awarded agreements)
- Same for awarded agreements, I am seeing both banners (the banner for other agreement types and the banner for awarded agreements)
#3561 
look at what changed section
> refactor: ux feedback from temp ui

- frontend/cypress/e2e/agreementList.cy.js
- frontend/cypress/e2e/budgetChangeRequest.cy.js
- frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
- frontend/src/pages/agreements/details/AgreementDetails.jsx
This PR fixes the edit button logic in the Agreement List so that the edit button is disabled when the agreement is either awarded or not developed yet. Key changes include:
- Modifying the AgreementDetails component to render the edit section only when both edit mode and editability conditions are met.
- Updating the AgreementTableRow logic to incorporate additional conditions (agreement type not developed and awarded) when determining editability and locked messages.
- Adjusting Cypress tests to validate the new behavior and adding extra wait time in one test for improved stability.
- fixes #3778 
1. e2e tests pass or:
2. login as system owner
3. goto agreement list
4. look for agreement DIRECT ALLOCATION 2: African American Child and Family Research Center
5. edit button will be …
> fix: 🐛 Agreement List edit button logic

- frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Adds `line_description` and `comments` fields to Budget Line export
N/A - customer expressed this as a vital need
Attempt to do an export of budget lines
N/A
> Adding comments and line_description fields to BL export

- frontend/cypress/e2e/agreementDetails.cy.js
- frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
- frontend/src/helpers/agreement.helpers.js
- frontend/src/pages/agreements/details/AgreementDetails.test.js
- frontend/src/pages/agreements/details/AgreementDetailsView.jsx
> This PR updates the agreement type label logic so that non-GCS contract agreements are shown as "AA" rather than "Contract". The changes update the helper function used for label generation, adjust the details view to use the new helper, and update tests (unit, integration, and e2e) to verify the new behavior.
>
> Updated AgreementDetailsView to use getAgreementType from agreement.helpers.
Revised tests in AgreementDetails.test.js and agreementDetails.cy.js to reflect the "AA" label when applicable.
Updated AgreementTableRow and the agreement.helpers.js to centralize the agreement type logic.
Update the agreement type label to AA if a contract with procurement shop that is not GCS. fixed #3778 AC 2
#3778 
1. all e2e test pass
2. go to agreement list and check AA agreement type
3. click …
> fix: update agreement type label to AA for non contract agreement

- backend/data_tools/src/disable_users/disable_users.py
Updating the first condition and initial check for an inactive user to further only look at currently active users.  Thusly excluding users who are not already active even if they had a prior session.
N/A
Verify that it's not trying to re-disable users that were previously marked as disabled but that had a previous session
N/A
> Updates disable user script to only look at active users

- frontend/src/pages/help/FAQ.jsx
A fix where extra characters were accidentally added to an FAQs content tag which resulted in the FAQ answer disappearing.
> docs: update faq.jsx

- frontend/src/components/UI/Cards/BudgetCard/ReceivedFundingCard.jsx
- frontend/src/components/UI/Cards/BudgetCard/ReceivedFundingCard.test.jsx
- frontend/src/components/UI/DataViz/LineGraph/ReverseLineGraph.jsx
This PR fixes the calculation for the received percentage in the budgeting cards and updates the relevant graph and tests accordingly.
- Introduces a calculation for the received percentage using the calculatePercent helper.
- Updates the ReverseLineGraph component to add a test identifier.
- Adds comprehensive tests for the ReceivedFundingCard component.
- closes #3787 
1. unit test pass
2. visit `/cans/515/funding` select FY 2023
3. check the Funding Received YTD card
> fix: add calculation for received percentage and update graph data

- frontend/Dockerfile.azure
Removes specific version of unzip specified in frontend azure dockerfile. Renovate nor dependabot will keep it up to date so just not pinning it. 
previous specified version is no longer available
CI/CD tests
> Removing specific version of unzip in apt command of frontend dockerfile

- frontend/cypress/e2e/components.cy.js
This PR aims to improve performance in the component tests by targeting agreement 9 rather than 1. The key changes include:
- Removing the "should display date range picker" test.
- Updating the URL in the test cases from "/agreements/1/budget-lines" to "/agreements/9/budget-lines".
1. e2e tests pass 
> test: improve perf on components test

- frontend/cypress/e2e/canList.cy.js
- frontend/src/pages/cans/list/CanList.jsx
- Add `return` statement. 
-  I believe filterCANsByFiscalYear() runs, but the callback doesn't return anything if we don't include the `return` statement — so filteredCANsByFiscalYear would be undefined.
- Fix CanList e2e tests.
> E2e tests and return stmt

- backend/ops_api/ops/services/budget_line_items.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
Fix budget lines list error when BLI has no amount
closes #3911
1. open budget_line_item table in DB
2. delete amount of BLI 15000
3. visit /budget-lines
4. should not break
> fix: fix budget lines list error when BLI has no amount

- backend/ops_api/ops/schemas/budget_line_items.py
- backend/ops_api/ops/services/budget_line_items.py
- backend/ops_api/tests/ops/can/test_budget_line_item.py
- frontend/src/components/Portfolios/PortfoliosComboBox/PortfoliosComboBox.jsx
This PR fixes a mismatch in portfolio IDs between the UI query parameters and the database response, ensuring the agreement list filters correctly by portfolio.
Frontend: Use actual portfolio IDs instead of index-based IDs in the combo box options.
Backend service & schema: Emit portfolios as objects with id and name, sorted by name.
Tests: Update expectations to match the new object format for portfolios.
--Copilot
Closes #3904 
Agreement list filtering by portfolio should show the correct agreements
> OPS-3904: agreement list filter by portfolio bug fix

- frontend/src/components/CANs/CANTable/CANTableRow.jsx
- frontend/src/components/CANs/CANTable/CANTableRow.test.jsx
Fix UI display to show 'TBD' when total funding or funding received is zero; adds NO_DATA constant usage and unit tests for these scenarios.
- Import and use NO_DATA for zero total funding in the table row.
- Add tests to verify "TBD" shows when total_funding or received_funding is 0.
- Retain existing conditional rendering for funding received.
- closes #3862 
1. tests pass or
1. look over steps in 3862
> fix: ♻️ display 'TBD' when totalFunding or totalReceived is 0

- frontend/src/components/Agreements/AgreementDetailsCards/AgreementTotalCard/AgreementTotalCard.jsx
- frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.jsx
- frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.jsx
- frontend/src/components/Agreements/ProcurementShopSelectWithFee/ProcurementShopSelectWithFee.jsx
- frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
- frontend/src/components/Projects/ProjectAgreementSummaryCard/ProjectAgreementSummaryCard.jsx
- frontend/src/helpers/budgetLines.helpers.js
- frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
This PR refactors prop-type handling by replacing PropTypes with JSDoc imports, adds nullish defaults for potentially undefined values, and tightens helper validations.
- Use `??` defaults for amounts and arrays to avoid `undefined`
- Swap out PropTypes for imported JSDoc typedefs
- Add runtime checks in helper functions to validate array inputs
> refactor: update prop types and improve default values across components

- .github/renovate.json
Given @rajohnson90's great work to alleviate the breaking changes from Marshmallow 4, we no longer need to have renovate artificially ignoring any updates to marshmallow. This essentially reverses part of #3909
#3898
Let renovate run according to its schedule or force a manual run and note the logs
N/A
> Removes prohibition on renovate updating marshmallow

- frontend/vite.config.mjs
The `JSON.stringify(VITE_BACKEND_DOMAIN)` was incorrect and would cause the domain comparison to fail.
- e2e tests pass
> fix: fixes Vite domain comparison

- frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
- frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.hooks.js
- frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.jsx
- frontend/src/components/Projects/ProjectAgreementSummaryCard/ProjectAgreementSummaryCard.jsx
- frontend/src/pages/agreements/details/AgreementDetailsView.jsx
This PR updates how the procurement shop default option is handled throughout the agreement creating wizard, ensuring that both the “default” and “no proc shop” cases display correctly and allow agreement creation.
1. go through the creating agreement wizard
2. use default proc shop 
3. should allow creating an agreement.
4. go through the creating agreement wizard
5. use no proc shop
6. should allow creating an agreement.
> fix: procurement shop default option handling

- .pre-commit-config.yaml
Adds a pre-commit hook to lint the renovate bot config file(s) if changed. 
**You'll want to run `pre-commit` locally at the repo root.**
No existing issue really, but I do credit the scholar and a gentleman, @tomwillis608 for advertising this discovery and being the change agent he is. 
You'll want to run `pre-commit` locally at the repo root. Then try staging a change locally to renovatebot config and watching the output! 
N/A
> Adding a renovate linter in pre-commit

- frontend/cypress/e2e/agreementDetails.cy.js
- frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
- frontend/src/helpers/agreement.helpers.js
- frontend/src/helpers/utils.js
- frontend/src/pages/agreements/agreements.constants.js
- frontend/src/pages/agreements/details/Agreement.jsx
- frontend/src/pages/agreements/details/AgreementDetails.test.js
This PR reverts the temporary UI handling of AA (Assisted Acquisition) agreement types to use a proper AA enum value instead of dynamically determining AA status based on procurement shop and contract type.
- Adds explicit "AA" enum to AgreementType constants
- Simplifies agreement type detection logic by removing procurement shop dependencies
- Updates test cases to reflect the new AA agreement type handling
This PR closes #4131 and essentially reverses #3807
2. visit agreement 5 and should see correct tag from BE and temp banner 
> OPS-4131: revert AA agreement type from temporary UI

- backend/models/budget_line_items.py
- backend/models/change_requests.py
- backend/openapi.yml
- backend/ops_api/ops/schemas/change_requests.py
- backend/ops_api/ops/utils/change_requests_helpers.py
- backend/ops_api/tests/ops/agreement/test_agreement_change_requests.py
- backend/ops_api/tests/ops/budget_line_items/test_budget_line_item_change_requests.py
- backend/ops_api/tests/ops/utils/test_change_requests_helpers.py
- backend/ops_api/tests/ops/workflows/test_change_requests.py
- Change the `in_review` attribute on the BLIs to indicate if the BLI or its parent agreement has a change request
- Rename `has_proc_shop_field_names_change`
[#4157](https://github.com/HHS/OPRE-OPS/issues/4157)
All tests pass successfully.
N/A
N/A
> Extend 'in_review' to include agreement change requests.

- frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Add project title to budget line item export
This PR closes #4141 
1. go to /budget-lines
2. apply a filter for faster export(e.g. Fiscal year = 2045)
3. click Export
4. verify the project title is in the export table
> feat: add project title to budget line item export

- backend/data_tools/data/can_data.json5
- backend/models/cans.py
- backend/ops_api/ops/services/cans.py
- backend/ops_api/tests/ops/can/test_can.py
- backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
- frontend/cypress/e2e/canDetail.cy.js
- frontend/cypress/e2e/canList.cy.js
- frontend/src/components/CANs/CANFundingInfoCard/CANFundingInfoCard.jsx
- frontend/src/components/CANs/CANTable/CANTableRow.helpers.js
- frontend/src/components/CANs/CANTable/CANTableRow.helpers.test.js
- frontend/src/pages/cans/list/CanList.helpers.js
- frontend/src/pages/cans/list/CanList.helpers.test.js
- frontend/src/pages/cans/list/CanList.jsx
This PR fixes a bug in the CANs filter functionality by moving fiscal year filtering from the frontend to the backend. The change eliminates the separate filterCANsByFiscalYear function and integrates the filtering logic directly into the backend API service.
- Refactored fiscal year filtering from frontend to backend for better performance and consistency
- Updated CANs service to handle fiscal year filtering with proper logic for 0-year, 1-year, and multi-year CANs
- Fixed display logic for 0-year active periods
closes #4205 
1. go to /cans
2. can G995679 should be in the table with Active Period 0 year
3. click on the CAN number, the can details page should display correct information
4. all tests pass
> OPS-4205: CANs filter bug fix

- frontend/cypress/e2e/editBudgetLineByPowerUser.cy.js
- frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
This PR enables PowerUsers to edit the CAN for Budget Line Items in Contract agreements.
#4289 
> feat: PowerUser can edit BLI CAN for Contract

- backend/data_tools/src/load_cans/utils.py
- backend/data_tools/tests/load_cans/test_load_cans.py
Some tweaks to CAN importing/upserting script including:
* supporting the DRY_RUN environment variable
* Added some more logging for sanity
* Cleaning up comments
* refactoring of code handling existing vs. new can
N/A
> Improvements to can upsert script

- frontend/cypress/e2e/editBudgetLineByPowerUser.cy.js
- frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
- frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
- frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
This PR enables power users to edit the "obligate by date" field in budget line items.
Key changes:
- Removes the isSuperUser parameter and related logic that disabled the obligate by date field
- Updates tests to verify that power users can now edit both amount and date fields
- Simplifies the BudgetLinesForm component by removing conditional date field disabling
closes #4359 
1. login as power user
2. goto /agreements/10
3. edit the planned budget line's obligate by date and save changes
4. ensure the changes are persisted
> feat: allows power user to edit obligate by date

- AGENTS.md
- README.md
Updates documentation to clarify Docker Compose usage options by providing multiple command variations and explicitly marking the --watch flag as optional with a note about system overhead.
- Adds standard Docker Compose commands without the watch flag
- Adds detached mode option with -d flag
- Clarifies that the --watch flag is optional and mentions its system overhead implications
> docs: updates readme to reflect the watch flag is optional

- frontend/src/helpers/agreement.helpers.js
- frontend/src/helpers/agreement.helpers.test.js
• Rename `isAfterApproval` parameter to `includeDraftBLIs` in `calculateAgreementTotal` function for better clarity
• Update corresponding test descriptions to match the new parameter name
• Minor code formatting improvements for better readability
The new parameter name `includeDraftBLIs` more clearly describes what the boolean controls - whether to include DRAFT budget line items in the calculation, rather than the more ambiguous `isAfterApproval`.
> refactor: improve parameter naming clarity for calculateAgreementTotal

- frontend/bun.lock
- frontend/package.json
- 7.1.8 has a regression
- supersedes https://github.com/HHS/OPRE-OPS/pull/4486
> feat: ✨ updates vite to 7.1.9

- frontend/src/helpers/agreement.helpers.js
- frontend/src/pages/agreements/list/AgreementsList.jsx
This PR refactors fee calculation in the agreements list by replacing a local helper function with a backend-sourced calculation and improves type safety and null handling in the agreement subtotal calculation.
- Replaced getProcurementShopSubTotal with getAgreementFeesFromBackend for consistent fee calculation
- Added null safety check for budget line items in getAgreementSubTotal
- Improved JSDoc type annotation for better TypeScript integration
#4447
1. goto agreements list
2. click on the export
3. review results
- [-] 90%+ Code coverage achieved
> fix: export agreement list fee calculation

- .github/workflows/e2e_test_reusable.yml
• Eliminates noisy DBus and terminal warnings from Cypress E2E tests in GitHub Actions while maintaining test functionality
• Optimizes CI performance by installing minimal required packages with --no-install-recommends
• Improves compatibility across Ubuntu versions by using standard package names
• Added runtime dependencies: Install minimal system packages (dbus-x11, xvfb, libgtk-3-0, etc.) required for headless browser operation
• Wrapped Cypress execution in dbus-run-session to provide proper DBus context and eliminate warnings
• Fixed artifact upload path to include .log extension matching generated log files
• Optimized package installation with --no-install-recommends flag and Ubuntu 22.04 compatible package names
• Official Cypress GitHub Action: Attempted but incompatible with …
> fix: suppress Cypress DBUS and terminal noise in CI
